### ISSUE TITLE
cluster health throws error with misconfigured cluster

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2029]
## Expected Behavior

I'd expect `sensuctl cluster health` to handle a misconfigured cluster of non-existence nodes in `initial-cluster`.

## Current Behavior

```
[root@sensu-backend-peer1 ~]# sensuctl cluster health
Error: json: cannot unmarshal object into Go struct field ClusterHealth.Err of type error
```

## Steps to Reproduce (for bugs)

Configure 2 node cluster with a 3rd non-existent node in `initial-cluster` and then run `sensuctl cluster health`.  I think that's how I produced the error.

YAML used where `backend3` doesn't exist.

```yaml
---
listen-client-urls: http://0.0.0.0:2379
listen-peer-urls: http://0.0.0.0:2380
initial-cluster: backend1=http://192.168.52.21:2380,backend2=http://192.168.52.22:2380,backend3=http://192.168.52.26:2380
initial-advertise-peer-urls: http://192.168.52.21:2380
initial-cluster-state: new
name: backend1
```

## Context

Was working on sensu-puppet and misconfigured my test environment which resulted in errors getting cluster health.  CC @ghoneycutt.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensuctl version 2.0.0-nightly#204a7cb, build 204a7cb3a5ff7aa7d26fa943fa5d3bea926422f1, built 2018-09-04T09:21:21+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7
