### ISSUE TITLE
sensu-agent --labels cmdline arg not working as expected

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2357]
## Expected Behavior
sensu-agent start --labels "hey=now" should populate entity metadata labels with "hey" key set to "now" value

## Current Behavior
When --labels "hey=now" is used sensuctl entity info  shows labels as null... even if labels are set in agent.yaml

## Steps to Reproduce (for bugs)

1. config agent.yaml with labels defined
```
cat agent.yml
---
##
# agent configuration
##
subscriptions: "dev"
labels:
  pumpkin: spice 
  chia: latte
```
2. start agent:
`sudo -u sensu sensu-agent start`
3. confirm labels are populated with sensuctl entity info --format yaml
```
type: Entity
spec:
  deregister: false
  deregistration: {}
  entity_class: agent
  last_seen: 1542327093
  metadata:
    annotations: null
    labels:
      chia: latte
      pumpkin: spice
    name: sensu-localdomain
    namespace: default
```
4. start agent with --labels "hey=now"
`sudo -u sensu sensu-agent start --labels "hey=now"`
5.  use sensuctl entity info --format yaml   and see labels are null
```
type: Entity
spec:
  deregister: false
  deregistration: {}
  entity_class: agent
  last_seen: 1542327178
  metadata:
    annotations: null
    labels: null
    name: sensu-localdomain
    namespace: default
```
## Your Environment
fedora 28
sensu-go beta8
