### ISSUE TITLE
Backend can lockup when agents crash during registration

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2431]
It appears that a simple round robin check request does not get published if more than one entity is subscribed to the check. This occurs in a single and clustered environment.

## Expected Behavior
When a check's round robin field is set to `true`, I would expect the check to execute in a round robin fashion. For all entities subscribed to that check, only one entity will execute it each time it is published.

## Current Behavior
Schedulerd complains that there is an error publishing the round robin check request:
```
Nov 28 03:46:28 ip-10-0-1-171 sensu-backend[3404]: {"check":"round-robin","component":"schedulerd","error":"context deadline exceeded","level":"error","msg":"error publishing round robin check request","time":"2018-11-28T03:46:28Z"}
```
https://github.com/sensu/sensu-go/blob/3860ab4f37d6dc7b16a8650b040637871b10fa41/backend/schedulerd/round_robin_scheduler.go#L79

## Possible Solution
Investigate the `context deadline exceeded` error thrown by `PublishDirect`.
https://github.com/sensu/sensu-go/blob/3860ab4f37d6dc7b16a8650b040637871b10fa41/backend/schedulerd/round_robin_scheduler.go#L60-L61

## Steps to Reproduce (for bugs)
1. create the following check:
```
spec:
  check_hooks: []
  command: echo round-robin
  cron: ""
  handlers: []
  high_flap_threshold: 0
  interval: 10
  low_flap_threshold: 0
  metadata:
    annotations: null
    labels: null
    name: round-robin
    namespace: default
  output_metric_format: ""
  output_metric_handlers: []
  proxy_entity_name:
  publish: true
  round_robin: true
  runtime_assets: []
  stdin: false
  subdue: null
  subscriptions:
  - round-robin
  timeout: 0
  ttl: 0
type: CheckConfig
```
2. start 2 agents subscribed to `round-robin`
3. observe that no events are created for the check `round-robin`
4. observe the errors logged on the backend(s)

## Context
Round robin checks should work with more than one entity subscribed. That is the defining use case for a round robin check.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/9f7978204c67a1186847ba9ef80492cebe952048
* Installation method (packages, binaries, docker etc.): packages deployed from terraform in aws
* Operating System and version (e.g. Ubuntu 14.04): backend: Ubuntu 16.04

**Comment by echlebek** [comment]
This is a recent regression. I'm figuring out the commit that caused it.

**Comment by echlebek** [comment]
So, I actually wasn't able to reproduce the issue. (tip of master, docker)

I used the check you pasted above, plus the following docker-compose:

```
version: '3'
services:
  backend1:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name backend1 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend1:2380 --state-dir /var/lib/sensu/etcd1 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug --debug
    hostname: backend1
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
      - "8080:8080"
      - "8081:8081"
      - "6060:6060"
  backend2:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name backend2 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend2:2380 --state-dir /var/lib/sensu/etcd2 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend2
    restart: always
    ports:
      - "12379:2379"
      - "12380:2380"
      - "18080:8080"
      - "18081:8081"
  backend3:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --name backend3 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend3:2380 --state-dir /var/lib/sensu/etcd3 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend3
    restart: always
    ports:
      - "22379:2379"
      - "22380:2380"
      - "28080:8080"
      - "28081:8081"
  agent1:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend1:8081 --subscriptions test,round-robin --log-level debug
    hostname: agent1
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
  agent2:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend2:8081 --subscriptions test,round-robin --log-level debug
    hostname: agent2
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
  agent3:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend3:8081 --subscriptions test,round-robin --log-level debug
    hostname: agent3
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
```

I see the following events:
```
  Entity      Check        Output      Status   Silenced             Timestamp            
 ──────── ───────────── ───────────── ──────── ────────── ─────────────────────────────── 
  agent1   keepalive                        0   false      2018-11-27 22:58:56 -0800 PST  
  agent1   round-robin   round-robin        0   false      2018-11-27 22:58:53 -0800 PST  
                                                                                          
  agent2   keepalive                        0   false      2018-11-27 22:58:54 -0800 PST  
  agent2   round-robin   round-robin        0   false      2018-11-27 22:58:33 -0800 PST  
                                                                                          
  agent3   keepalive                        0   false      2018-11-27 22:58:55 -0800 PST  
  agent3   round-robin   round-robin        0   false      2018-11-27 22:58:43 -0800 PST  
```
