### ISSUE TITLE
Dashes are not valid characters in token names

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#2507]
Following the examples in the documentation and using dashes in token names causes errors for parsing the template.

## Expected Behavior
Tokens using dashes should not cause parsing errors.

## Current Behavior
Using a dash causes the following error:

> could not parse the template: template: :1: bad character U+002D '-'

Using other characters, such an underscore, does not cause this error.

## Steps to Reproduce (for bugs)

1. Assign a token to an agent with a dash in the name (as in the documented examples (e.g. memory-warning))
2. Create a check that references this token (e.g. .labels.memory-warning)
3. On the dashboard, the check should be reported as unknown with the above error message

## Context

```
# sensuctl check info linux-memory-check
=== linux-memory-check
Name:              linux-memory-check
Interval:          60
Command:           /opt/sensu-plugins-ruby/embedded/bin/check-memory-percent.rb {{ .labels.memory-warning | default 90 }} -c {{ .labels.memory-critical | default 95 }}
Cron:              
Timeout:           0
TTL:               0
Subscriptions:     linux
Handlers:          mail
Runtime Assets:    
Hooks:             
Publish?:          true
Stdin?:            false
Proxy Entity Name: 
Namespace:         default
Metric Format:     
Metric Handlers:   
```
```
# cat agent.yml 
---
##
# agent configuration
##
#name: ""
#namespace: "default"
subscriptions:
  - linux
backend-url:
  - "ws://127.0.0.1:8081"

labels:
  memory-warning: 85
  memory-critical: 95

##
# authentication configuration
##
#user: "agent"
#password: "P@ssw0rd!"

##
# api configuration
##
#api-host: "127.0.0.1"
#api-port: 3031
#disable-api: false

##
# socket configuration
##
#disable-sockets: false
#socket-host: "127.0.0.1"
#socket-port: 3030

##
# statsd configuration
##
#statsd-disable: false
#statsd-event-handlers: ""
#statsd-flush-interval: 10
#statsd-metrics-host: "127.0.0.1"
#statsd-metrics-port: 8125

##
# other
##
#cache-dir: "/var/cache/sensu/sensu-agent"
#config-file: ""
#deregister: false
#deregistration-handler: ""
#keepalive-timeout: 120
#keepalive-interval: 20
#extended-attributes: ""
#log-level: "warn"
#redact: ""

```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensu-backend version 5.0.0#b6a6ddb, build b6a6ddb48723c75dd240f43bec94311fc8011332, built '2018-12-03T22:38:30+0000'
sensu-agent version 5.0.0#b6a6ddb, build b6a6ddb48723c75dd240f43bec94311fc8011332, built '2018-12-03T22:38:30+0000'
sensuctl version 5.0.0#b6a6ddb, build b6a6ddb48723c75dd240f43bec94311fc8011332, built '2018-12-03T22:38:30+0000'
* Installation method (packages, binaries, docker etc.):  Packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04

![image](https://user-images.githubusercontent.com/5530473/49674585-4f8b5500-fa27-11e8-960f-14e47a0f2475.png)
