### ISSUE TITLE
Update check ttl output

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#2538]
After a check's ttl has expired, the status of the check's event changes to 1 and the output changes to `Last check execution was x seconds ago`. This output is never updated, so the statement is not entirely accurate.

## Expected Behavior
Check output after an expired ttl of 10 seconds reads:
- `Last check execution was 10 seconds ago` and is constantly updated to reflect the current time, ex: `Last check execution was 123 seconds ago`.
- `Last check execution was at 2018-12-14 20:29:58 +0000 UTC`

## Current Behavior
Stale check output after an expired ttl of 10 seconds reads:
- `Last check execution was 10 seconds ago` and never changes.

## Possible Solution
Implement one of the expected behaviors.

## Steps to Reproduce (for bugs)
1. create the following check resource
```
type: CheckConfig
api_version: core/v2
metadata:
  name: ttl-check
  namespace: default
spec:
  check_hooks: null
  command: echo ttl
  handlers: []
  high_flap_threshold: 0
  interval: 1
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: []
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets: []
  stdin: false
  subdue: null
  subscriptions:
  - schedules
  timeout: 0
  ttl: 10
```
2. let the check execute at least once
3. change the check command to a hanging process `sensuctl check set-command ttl-check 'sleep infinity'`
4. observe the event data has the stale check output of `Last check execution was 10 seconds ago`

## Context
Option 1 is rather complex, so I wouldn't necessarily suggest adding that logic. However, Option 2 captures a more accurate description for an expired check ttl.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.0.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.01
