### ISSUE TITLE
Agent doesn't parse annotations from agent.yml config files

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2554]
I should be able to define an annotations dictionary into agent.yml and have agent's entity populate annotations metadata.  

agent.yml:
```
---
##
# agent configuration
##
name: "annotate_this"
labels:
  dog: "2.0"
  cat: "1.0"

annotations:
  test: "this is a test"
```

## Expected Behavior
annotations should be uploaded into entity config when agent is started

## Current Behavior
no annotation metadata in entity config

## Steps to Reproduce (for bugs)
1. use above agent.yml 
2. restart agent server
3. sensuctl entity info annotate_this --format json
4. confirm annotations not in entity info

## Environment
using sandbox VM
```
rpm -qa |grep sensu
sensu-go-backend-5.0.1-1.x86_64
sensu-plugins-ruby-0.2.0-1.el7.x86_64
sensu-go-cli-5.0.1-1.x86_64
sensu-go-agent-5.0.1-1.x86_64
````
