### ISSUE TITLE
Unable to use self-signed certs with backend

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2575]
## Expected Behavior

I'd expect a self-signed certificate to work.

## Current Behavior

```
[root@sensu-backend ~]# sensuctl configure -n --url 'https://localhost:8080' --username 'admin' --password 'P@ssw0rd!'

Error: unable to authenticate with error: Get https://localhost:8080/auth: x509: certificate signed by unknown authority
```

## Steps to Reproduce (for bugs)

Generate CA and cert:
```
 openssl req -newkey rsa:2048 -nodes -keyout /etc/sensu/ca_key.pem -x509 -days 365 -out /etc/sensu/ca.pem -subj '/CN=localhost'
openssl req -newkey rsa:2048 -nodes -keyout /etc/sensu/key.pem -out /etc/sensu/localhost.csr -subj '/CN=localhost'
openssl x509 -req -in /etc/sensu/localhost.csr -CA /etc/sensu/ca.pem -CAkey /etc/sensu/ca_key.pem -CAcreateserial -out /etc/sensu/cert.pem -days 365 -sha256
```
Configure backend:
```yaml
---
state-dir: "/var/lib/sensu/sensu-backend"
cert-file: "/etc/sensu/cert.pem"
key-file: "/etc/sensu/key.pem"
trusted-ca-file: "/etc/sensu/ca.pem"
insecure-skip-tls-verify: true
```

Try to run `sensuctl configure`:

```
[root@sensu-backend ~]# sensuctl configure -n --url 'https://localhost:8080' --username 'admin' --password 'P@ssw0rd!'

Error: unable to authenticate with error: Get https://localhost:8080/auth: x509: certificate signed by unknown authority
```

## Context

Working on better support for SSL with sensu-puppet module and am having trouble testing SSL to verify the module fully supports SSL enabled configurations.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.0
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
