### ISSUE TITLE
Check interval should not be required for checks set to publish:false

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#2623]
The check `interval` or `cron` attribute(s) should not be required if a check is set to `"publish": false`. 

## Expected Behavior

This should be a valid check definition: 

```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: helloworld
  namespace: default
spec:
  command: echo "hello, world!"
  publish: false
```

## Current Behavior

When attempting to create a CheckConfig using the above definition, I get the following error:

```
$ sensuctl create -f helloworld.yaml
error validating resource 0 (/api/core/v2/namespaces/default/checks/helloworld): check interval must be greater than 0 or a valid cron schedule must be provided
Error: resource validation failed
```

## Possible Solution

No `interval` or `cron` schedule should be required when a CheckConfig has `"publish": false` set. 

## Steps to Reproduce (for bugs)

1. Create a CheckConfig definition from the example provided above
2. `sensuctl create -f` the definition
3. :boom: 

## Context

I'm working on a prototype remediation handler, so I need to configure checks that aren't scheduled to be published on any kind of schedule. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.0.x
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): debian stretch
