### ISSUE TITLE
sensu check using asset and sudo - command not found

### ISSUE THREAD

**Issue by craigpfeiffer** [sensu/sensu-go#2629]
running `sudo check-fs-writable.rb -a` using a ruby runtime asset as well as the plugin package as an asset.  when the check runs i am left with an error 
`sudo: check-filesystem-writable.rb: command not found`

## Expected Behavior
`sudo check-fs-writable.rb -a` should output `CheckFSWritable OK: All filesystems are writable`

## Current Behavior
the current output is `sudo: check-filesystem-writable.rb: command not found`

## Possible Solution
i don't know a possible solution, but it appears to be tied to `$PATH`

## Steps to Reproduce (for bugs)
add sensu to sudoers file
use the following check config
```
---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: writable_filesystem 
spec:
  publish: true
  command: sudo check-fs-writable.rb -a
  subscriptions:
  - production
  interval: 60
  runtime_assets:
  - sensu-ruby-2.4.4
  - sensu-plugins-filesystem 
```

## Context
executing the command locally with the absolute path as sensu user with sudo works fine.  in the check i added `sudo ls {{ absolute path to plugin }}` and could see that.  `sudo echo $PATH` also returned the proper results.  i also added the absolute path to the check for ruby and the plugin and that worked fine, which brings me back to something funky with the path is happening.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):5.1
* Installation method (packages, binaries, docker etc.):backend container, agent rpm
* Operating System and version (e.g. Ubuntu 14.04):centos 7, amazon linux
