### ISSUE TITLE
assets filtering is not working

### ISSUE THREAD

**Issue by Surian** [sensu/sensu-go#2647]
## Expected Behavior

Assets should be filtered by the agent if a filter has been specified on the asset.

## Current Behavior

Asset download fails with error even if the filter is existing:
{"asset":"system32-linux","component":"asset-manager","entity":"srv-cops-01","error":"**ReferenceError: 'oldarch' is not defined**","filters":["oldarch"],"level":"error","msg":"**error filtering entities from asset**","time":"2019-01-30T15:42:15+01:00"}

Filters are not working on assets.

## Steps to Reproduce (for bugs)
1. Create a filter
```
type: EventFilter
api_version: core/v2
metadata:
  name: oldarch
  namespace: sandbox
spec:
  action: allow
  expressions:
  - entity.system.arch == '386'
  runtime_assets: []
```
2. Create an asset using the filter
```
type: Asset
api_version: core/v2
metadata:
  name: system32-linux
  namespace: sandbox
spec:
  filters:
  - oldarch
  sha512: 9c793327bd2f791f5ea99d504dc8441548c7c53eaa4e28b583945c0b4197097e979b8a651b5e687d92aa147925aa596b6c51c0ceb2675abc91ab2cf01b9d618b
  url: https://asset-url/system32-linux.tar.gz
```
3. Create a check using the asset
```
type: CheckConfig                                                                                                 
api_version: core/v2
metadata:
  name: disk-root
  namespace: sandbox
spec:
  check_hooks: null
  command: disk -w {{ .labels.diskrootwarning | default 20 }}% -c {{ .labels.diskrootcritical
    | default 10 }}% /
  env_vars:
  - LANG=C
  handlers:
  - slack
  - email
  high_flap_threshold: 0
  interval: 5
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: []
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets:
  - system32-linux
  stdin: false
  subdue: null
  subscriptions:
  - linux
  timeout: 10
  ttl: 0
```
4. Start agent

Asset download will fail:
```
{"component":"agent","level":"info","msg":"message received","payload":"{\"config\":{\"command\":\"disk -w {{ .labels.diskrootwarning | default 20 }}% -c {{ .labels.diskrootcritical | default 10 }}% /\",\"handlers\":[\"slack\",\"email\"],\"high_flap_threshold\":0,\"interval\":5,\"low_flap_threshold\":0,\"publish\":true,\"runtime_assets\":[\"system-linux\",\"system32-linux\"],\"subscriptions\":[\"linux\"],\"proxy_entity_name\":\"\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":0,\"timeout\":10,\"round_robin\":false,\"output_metric_format\":\"\",\"output_metric_handlers\":[],\"env_vars\":[\"LANG=C\"],\"metadata\":{\"name\":\"disk-root\",\"namespace\":\"sandbox\"}},\"assets\":[{\"url\":\"https://asset-url/system-linux.tar.gz\",\"sha512\":\"306b1aeaa8f271be93c952054d2c63f62f4689cf96cd3333929ac9c4453c7e90151e23d0b496defed43664fff30b214c08a6b647403f90dae8e5101f4e9e5ed7\",\"filters\":[],\"metadata\":{\"name\":\"system-linux\",\"namespace\":\"sandbox\"}},{\"url\":\"https://asset-url/system32-linux.tar.gz\",\"sha512\":\"9c793327bd2f791f5ea99d504dc8441548c7c53eaa4e28b583945c0b4197097e979b8a651b5e687d92aa147925aa596b6c51c0ceb2675abc91ab2cf01b9d618b\",\"filters\":[\"oldarch\"],\"metadata\":{\"name\":\"system32-linux\",\"namespace\":\"sandbox\"}}],\"hooks\":null,\"issued\":1548859374}","time":"2019-01-30T15:42:15+01:00","type":"check_request"}
{"component":"agent","level":"info","msg":"scheduling check execution: disk-root","time":"2019-01-30T15:42:15+01:00"}
{"asset":"system32-linux","component":"asset-manager","entity":"srv-cops-01","error":"ReferenceError: 'oldarch' is not defined","filters":["oldarch"],"level":"error","msg":"error filtering entities from asset","time":"2019-01-30T15:42:15+01:00"}
```

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.1
* Installation method (packages, binaries, docker etc.): Ubuntu packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04
