### ISSUE TITLE
Duplicate subscriptions on agent entities running proxy checks

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2930]
## Expected Behavior
Proxy check events on agent entities do not have duplicate subscriptions.

## Current Behavior
Proxy check events on agent entities have duplicate subscriptions.

## Possible Solution
Investigate where we append subscriptions to entities.

## Steps to Reproduce (for bugs)
1. Create the following check
```
type: CheckConfig
api_version: core/v2
metadata:
  name: ping-proxy
  namespace: default
spec:
  check_hooks: null
  command: ping -c 1 google.com
  handlers: []
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: []
  proxy_entity_name: "proxy"
  proxy_requests:
    entity_attributes:
    - entity.name == "staging-agent-0" || entity.name == "staging-agent-1"
    splay: true
    splay_coverage: 90
  publish: true
  round_robin: false
  runtime_assets: []
  stdin: false
  subdue: null
  subscriptions:
  - proxy
  timeout: 0
  ttl: 0
```
2. Start two entities `staging-agent-0` and `staging-agent-1` with a `proxy` subscription
3.  Run `sensuctl event info staging-agent-0 ping-proxy --format yaml`
4. Observe duplicate `entity:staging-agent-0` subscriptions in the event's entity
```
  entity:
    deregister: false
    deregistration: {}
    entity_class: agent
    last_seen: 1557342420
    metadata:
      labels:
        ec2_access_key: REDACTED
        secret: P@ssw0rd
      name: staging-agent-0
      namespace: default
    redact:
    - ec2_access_key
    subscriptions:
    - metrics
    - misc
    - round-robin
    - proxy
    - switches
    - entity:staging-agent-0
    - entity:staging-agent-0
```

## Context
This does not appear to be impacting the behavior of the proxy check, but it could have other unforeseen effects.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.6.0
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04
