### ISSUE TITLE
Dashboard Checks Page won't render if cron predefined schedules or intervals are used

### ISSUE THREAD

**Issue by jweede** [sensu/sensu-go#2993]
If any check is defined with one of the cron [predefined schedules or intervals](https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules) (e.g. `@daily` or `@every 1h`), the check dashboard refuses to render with the following message:

```
Error: Expression has only 1 part. At least 5 parts are required. 
```
![Screenshot from 2019-05-23 16-38-18](https://user-images.githubusercontent.com/135918/58284709-3548f780-7d79-11e9-84c8-66c6fe1201c8.png)

## Expected Behavior

Checks dashboard should render without error.

## Current Behavior

Checks dashboard fails to render. No obvious issue with `sensuctl check list`

## Steps to Reproduce (for bugs)
1. Define a check with a cron `@` interval and load it with `sensuctl create -f`. For example:
```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: box_reboot_check
  namespace: default
spec:
  command: "/etc/sensu/checks/check-reboot.sh"
  subscriptions: [standard]
  handlers: [normal]
  cron: "@hourly"
  publish: true
```

2. Navigate to `/default/checks`
3. Observe error

## Context

Easy enough to work around by using `interval` or a more explicit `cron` spec, but would prefer the dashboard work for all valid configurations.

## Your Environment

Installed from `deb https://packagecloud.io/sensu/stable/ubuntu bionic main` on ubuntu 18.04, running on AWS.

```
$ sensu-backend version
sensu-backend version 5.8.0#626c482, build 626c4826bad2f01dd6d5f4eaa35565a764ccb0be, built 2019-05-21T22:32:44Z
$ sensuctl version
sensuctl version 5.8.0#626c482, build 626c4826bad2f01dd6d5f4eaa35565a764ccb0be, built 2019-05-21T22:33:57Z
$ sensu-agent version
sensu-agent version 5.8.0#626c482, build 626c4826bad2f01dd6d5f4eaa35565a764ccb0be, built 2019-05-21T22:33:05Z
```
