### ISSUE TITLE
[BUG] cluster-role   license list is not enough to get license info as user

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3025]
This is really wacky give license LIST to cluster-role system:user isn't sufficient to access license info.  But granting '*' LIST to cluster-role system:user is sufficient.

Getting the license info is required to get edit functions to work in the web-ui for example, so really important for Enterprise RBAC.   

What's going on? Why is '*' LIST required. Is there a hidden resource that needs to be touched behind the curtains when sensuctl license info or the license API GET is invoked?

Here's my setup

I have a user named test
```
sensuctl user list --format yaml
type: User
api_version: core/v2
metadata: {}
spec:
  disabled: false
  groups:
  - cluster-admins
  username: admin
---
type: User
api_version: core/v2
metadata: {}
spec:
  disabled: false
  groups:
  - system:agents
  username: agent
---
type: User
api_version: core/v2
metadata: {}
spec:
  disabled: false
  username: test
```

And here's my system:user cluster role
```
sensuctl cluster-role info system:user --format yaml
type: ClusterRole
api_version: core/v2
metadata:
  name: system:user
spec:
  rules:
  - resource_names: null
    resources:
    - localselfuser
    verbs:
    - get
    - update
  - resource_names: null
    resources:
    - namespaces
    verbs:
    - get
    - list
  - resource_names: null
    resources:
    - license
    verbs:
    - list
```
Now sensuctl configure as test user
```
sensuctl license info
Error: unauthorized to perform action
```

Update my system:user role to use '*' LIST rule
```
type: ClusterRole
api_version: core/v2
metadata:
  name: system:user
spec:
  rules:
  - resource_names: null
    resources:
    - localselfuser
    verbs:
    - get
    - update
  - resource_names: null
    resources:
    - namespaces
    verbs:
    - get
    - list
  - resource_names: null
    resources:
    - '*'
    verbs:
    - list
```
now sensuctl license info works!!!!!!!
What other resource is involved?

## Expected Behavior
adding license LIST to cluster role should be sufficient to view the license info

## Current Behavior
need to '*' LIST to cluster role to view license info
