### ISSUE TITLE
The filter when attribute doesn't appear to be honored

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#3037]
## Expected Behavior
When using the filter `when` attribute, I expect Sensu to honor the filter during the time periods listed and to stop applying the filter outside of those same time periods.

## Current Behavior
The filter `when` attribute appears to be ignored entirely by Sensu Go.

## Steps to Reproduce (for bugs)

1. Create a handler and a check that is in a warning state. Apply the handler to the check.
2. Set up time periods based on your current system time to have the following filter "ignored"
```
api_version: core/v2
metadata:
  name: filter-warning-after-1035am
  namespace: default
spec:
  action: deny
  expressions:
  - event.check.status == 1
  when:
    days:
      all:
      - begin: 12:00AM
        end: 10:35AM
      - begin: 11:00PM
        end: 1:00AM
```
3. Apply the filter to the same handler made above
4. Observe that Sensu continues to filter the warning event after the system time passes the specified time period.

## Context
This would allow users to set up office hour times for filters.

## Your Environment

* Sensu version used: Sensu Go 5.9 for sensuctl, backend and agent.
* Installation method (packages, binaries, docker etc.): Packages
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by echlebek** [comment]
The attribute is indeed honoured - I wonder if there is a timezone issue at play?

**Comment by rgeniesse** [comment]
@echlebek I ensured my timezone was set to my local time, so my `when` time spans were correct. Were you able to get a test environment to honor it? I'd be curious to see what that looks like as I have been unsuccessful in my 3-4 attempts at this.

Another item to point out, when I apply the above filter and try to view it using `sensuctl` I get the following output:

```
sensuctl filter info filter-warning-after-1035am --format yaml
type: EventFilter
api_version: core/v2
metadata:
  name: filter-warning-after-1035am
  namespace: default
spec:
  action: deny
  expressions:
  - event.check.status == 1
  runtime_assets: null
```

The configured `when` attribute is no where to be seen. So that would appear to be a bug in `sensuctl` or the `when` attribute isn't being stored for some reason.

**Comment by cwjohnston** [comment]
@rgeniesse to re-test this on latest release so we can reprioritize if needed.

**Comment by echlebek** [comment]
@rgeniesse is this still an issue?

**Comment by rgeniesse** [comment]
It appears to still be an issue. Using this definition: 

```
type: EventFilter
api_version: core/v2
metadata:
  name: filter-warning-after-0210
  namespace: default
spec:
  action: deny
  expressions:
  - event.check.status == 2
  when:
    days:
      all:
      - begin: 12:00AM
        end: 2:14PM
      - begin: 2:15PM
        end: 2:21PM
```

I do not get any output for the `when` attribute using sensuctl:

```
type: EventFilter
api_version: core/v2
metadata:
  name: filter-warning-after-0210
  namespace: default
spec:
  action: deny
  expressions:
  - event.check.status == 2
  runtime_assets: null
```

And the filter just denies my exist status 2 event forever.

That and based on my time periods, the deny should have stopped after 2:21pm, but has not. I even attempted moving the the time period down to one and to follow UTC time.
