### ISSUE TITLE
proxy checks don't get scheduled

### ISSUE THREAD

**Issue by sjthespian** [sensu/sensu-go#3135]
##  Expected Behavior
There seems to be a bug with template variable and proxy checks that keeps them from getting scheduled in some situations. In my case, I have a pair or proxy checks that work on some entities but never appear on others.

## Current Behavior
The proxy checks are appearing on some entities but not others. The error message that appears in the log is less than helpful, it doesn't specify the check or the entity that is causing the error:
```
Jul 11 15:29:06 morpheus sensu-backend[19233]: {"component":"schedulerd","error":"unmatched token: template: :1:46: executing \"\" at \u003c.system.hostname\u003e: map has no entry for key \"hostname\"","level":"error","msg":"error executing check","time":"2019-07-11T15:29:06-07:00"}
```

## Possible Solution
To start with, the error message needs at least the entity name and check that are casing the error included in the message. At the moment, it is virtually impossible to debug what is causing that message.

## Steps to Reproduce (for bugs)
1. I haven't found a reproducible scenario for this yet

## Context

For one of my proxy checks I found that the issue was caused by the entity attribute in the check existing on a non-proxy host. When I removed that the check suddenly started working. To be specific, here is a stripped-down check definition (removing nulls and 0 values):
```
type: CheckConfig
api_version: core/v2
metadata:
  annotations:
    sensu.io.json_attributes: '{"occurrences":3,"refresh":3600,"dependencies":["keepalive"]}'
  name: proxy-http
  namespace: default
spec:
  command: check-http.rb -u {{ .labels.url }}
  handlers:
  - mailer
  interval: 180
  proxy_entity_name: ""
  proxy_requests:
    entity_attributes:
    - entity.labels.has_http_server == 'true'
    splay: true
    splay_coverage: 90
  publish: true
  round_robin: true
  runtime_assets:
  - sensu-ruby-runtime
  - sensu-ruby-runtime-armv7l
  - sensu-plugins-http
  subscriptions:
  - standalone
```
When I have `has_http_server: 'true'` defined on a non-proxy host, this doesn't get applied everywhere. If I remove that from all of the agents it will suddenly appear on all of the proxy hosts that have `has_http_server` set as a label.

I have yet to figure out what is causing this check to not be scheduled anywhere:
```
type: CheckConfig
api_version: core/v2
metadata:
  annotations:
    sensu.io.json_attributes: '{"occurrences":3,"refresh":3600,"dependencies":["keepalive"]}'
  name: proxy-fping
  namespace: default
spec:
  command: PATH=$PATH:/usr/lib/nagios/plugins check_fping {{ .system.hostname }}
  handlers:
  - mailer
  interval: 180
  proxy_entity_name: ""
  proxy_requests:
    entity_attributes:
    - entity.labels.needs_fping == 'true'
    splay: true
    splay_coverage: 90
  publish: true
  round_robin: true
  runtime_assets: null
  subscriptions:
  - standalone
```

Here is an example of an entity that is getting the http check above but not fping:
```
type: Entity
api_version: core/v2
metadata:
  labels:
    has_http_server: "true"
    needs_fping: "true"
    url: http://voipgw01.example.com/
  name: voipgw01
  namespace: default
spec:
  deregister: false
  deregistration: {}
  entity_class: proxy
  last_seen: 0
  subscriptions:
  - entity:voipgw01
  system:
    hostname: voipgw01
    network:
      interfaces: null
```

And one that gets both proxy checks:

## Your Environment
* Sensu version used - sensuctl, sensu-backend, sensu-agent: 5.11.0-4888
* Installation method: Deb x86_64 packages
* Operating System and version: Ubuntu 18.04
