### ISSUE TITLE
Template values require restart to populate in proxy checks

### ISSUE THREAD

**Issue by sjthespian** [sensu/sensu-go#3137]
## Expected Behavior
Proxy checks should update any templated values when those values change.

## Current Behavior
A proxy check that contains templated values will not see updates to those values without a restart of sensu-backend.

## Possible Solution
It appears that this is an issue with caching between the backend and etcd.

## Steps to Reproduce (for bugs)
1. Create a proxy check with templated values
2. Allow the check to run at least once
3. Change the label in the entity
4. Wait for the check to run again and see that it is still using the old value

## Context
Sample check:
```
type: CheckConfig
api_version: core/v2
metadata:
  annotations:
    sensu.io.json_attributes: '{"occurrences":3,"refresh":3600,"dependencies":["keepalive"]}'
  name: proxy-http
  namespace: default
spec:
  command: check-http.rb -u {{ .labels.url }}
  handlers:
  - mailer
  interval: 180
  proxy_entity_name: ""
  proxy_requests:
    entity_attributes:
    - entity.labels.has_http_server == 'true'
    splay: true
    splay_coverage: 90
  publish: true
  round_robin: true
  runtime_assets:
  - sensu-ruby-runtime
  - sensu-ruby-runtime-armv7l
  - sensu-plugins-http
  subscriptions:
  - standalone
```

Sample proxy entity:
```
type: Entity
api_version: core/v2
metadata:
  labels:
    has_http_server: "true"
    has_ssh: "true"
    has_ssl_cert: "true"
    needs_fping: "true"
    url: https://www.example.org/
  name: myhost.example.org
  namespace: default
spec:
  deregister: false
  deregistration: {}
  entity_class: proxy
  last_seen: 0
  subscriptions:
  - entity:myhost.example.org
  system:
    hostname: myhost.example.org
    network:
      interfaces: null
```

If you change the URL above with `sensuctl entity edit` it will not reflect in the check that is being run util the backend is restarted. This can be verified by looking at the event in the UI.

## Your Environment
* Sensu version used - sensuctl, sensu-backend, sensu-agent: 5.11.0-4888
* Installation method: Deb x86_64 packages
* Operating System and version: Ubuntu 18.04
