### ISSUE TITLE
sensu-backend stops updating most checks after some time

### ISSUE THREAD

**Issue by johannagnarsson** [sensu/sensu-go#3232]
## Expected Behavior
Backend should work as expected and schedule agent checks and process them.

## Current Behavior
After an undetermined amount of time, sensu-backend simply stops scheduling most checks, there are 5 checks that continue working for some reason, however those 5 checks are split between only 2 entities as I am in the middle of migrating over from sensu-core. There are more checks defined, and they are referenced in the logs, however there are no agents listening to the their subscriptions yet.

## Possible Solution
This bug seems to be related to the scheduler and/or assets as the only checks that continue working do not have any assets assigned to them and are executed out of the sensu-plugins-ruby directory (and are installed with the `sensu-install -p <plugin>` command

Currently the only solution is to restart sensu-backend.

## Steps to Reproduce (for bugs)

1. Start sensu-backend
2. Wait 0 to 12 hours
3. ???
4. Sensu-backend stops scheduling most checks

## Context
This is preventing us from migrating to sensu-go from sensu-core. 
Everything on the sensu backend is configured by puppet, including assets, checks, handlers, hooks etc. 
Here is a log file that covers about 4 minutes before and 4 minutes after it stops scheduling and processing checks.
[sensu-backend.log.gz](https://github.com/sensu/sensu-go/files/3532191/sensu-backend.log.gz)

Here is a definition of a check that stops being executed:
```yaml
type: CheckConfig
api_version: core/v2
metadata:
  name: cpu-check
  namespace: default
spec:
  check_hooks:
  - non-zero:
    - cpu-check-hook
  command: check-cpu.rb --idle-metrics idle,steal,guest,guest_nice,user -c {{.labels.cpu_critical
    | default 95}} -w {{.labels.cpu_warning | default 90}}
  env_vars: null
  handlers:
  - logstash
  - alerta
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: null
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets:
  - sensu-ruby-runtime-6
  - sensu-ruby-runtime-7
  - sensu-plugins-cpu-checks
  stdin: false
  subdue: null
  subscriptions:
  - linux
  - linux-ucs
  - linux-openstack
  timeout: 0
  ttl: 0
```

Check definition that continues being scheduled:
```yaml
type: CheckConfig
api_version: core/v2
metadata:
  name: mysql-check-replication
  namespace: default
spec:
  check_hooks: null
  command: /opt/sensu-plugins-ruby/embedded/bin/check-mysql-status.rb -i {{ .annotations.mysql_mycnf|
    default "~/.my.cnf"}} -d {{ .annotations.mysql_database | default "mysql"}} -C
    replication -h {{ .annotations.mysql_host | default "127.0.0.1"}}
  env_vars: null
  handlers:
  - webex
  - logstash
  - alerta
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: null
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets: null
  stdin: false
  subdue: null
  subscriptions:
  - mysql-replication
  timeout: 50
  ttl: 0
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensu-go-cli-5.11.1-5015.x86_64
sensu-go-agent-5.11.1-5015.x86_64
sensu-go-backend-5.11.1-5015.x86_64
* Installation method (packages, binaries, docker etc.):
RPM Packages via puppet
* Operating System and version (e.g. Ubuntu 14.04):
CentOS 7.6.1810
