### ISSUE TITLE
Bug: Proxy Check not firing hooks that use token subs

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3367]
proxy checks not firing hooks when hooks use token substitution. 

This is a follow up to discourse discussion here:
https://discourse.sensu.io/t/sensu-hooks-passing-parameters/1419

## How to reproduce
Create a proxy check:
```
type: CheckConfig
api_version: core/v2
metadata:
  name: test_proxy_check
spec:
  check_hooks:
  - critical:
    - test_hook
  - non-zero:
    - test_hook
  command: check_http -H  {{ .labels.hostname }}  -u /
  interval: 60
  proxy_requests:
    entity_attributes:
    - entity.entity_class == 'proxy'
    - entity.labels.proxy_type == 'website'
    splay: false
    splay_coverage: 0
  publish: true
  subscriptions:
  - proxy
  timeout: 0
  ttl: 0
```
create hook 
```
type: HookConfig
api_version: core/v2
metadata:
  name: test_hook
  namespace: poc
spec:
  command: echo "Proxy host {{ .labels.hostname }} "
  runtime_assets: null
  stdin: false
  timeout: 60
```
create proxy entity
```
type: Entity
api_version: core/v2
metadata:
  labels:
    hostname: sensu.io
    proxy_type: website
    pumpkin: pie
  name: sensu_website
  namespace: poc
spec:
  deregister: false
  deregistration: {}
  entity_class: proxy
  last_seen: 0
  sensu_agent_version: ""
  subscriptions:
  - web
  system:
    network:
      interfaces: null

```

So it appears as if the hook does not fire.  My best guest is backend is failing to process the token substitution and as a result doesn't end up attaching the hook into the synthetic check being generated to run on the real agent.

Backend log has a cryptic message
```
Oct 29 14:32:12 sensu-localdomain sensu-backend[31492]: {"component":"agentd","error":"check is invalid: check name must not be empty","level":"error","msg":"error handling message","payload":"\u0008\ufffd\ufffd\ufffd\ufffd\u0005\u0012\ufffd\u0005\n\u0005agent\u001a\ufffd\u0003\n\u0011sensu-localdomain\u0012\u0005linux\u001a\u0006fedora\"\u0006fedora*\u0002292\ufffd\u0003\n\u001a\n\u0002lo\u001a\u000b127.0.0.1/8\u001a\u0007::1/128\n\u001e\n\tenp0s31f6\u0012\u00118c:16:45:64:f3:ac\nQ\n\renp0s20f0u4u1\u0012\u0011e0:4f:43:96:59:d8\u001a\u000f192.168.0.54/24\u001a\u001cfe80::3eec:1e18:9527:7258/64\nJ\n\u0006wlp3s0\u0012\u001194:b8:6d:04:d4:3b\u001a\u000f192.168.0.47/24\u001a\u001cfe80::291f:d0c0:4c24:e58d/64\n-\n\u0006virbr0\u0012\u001152:54:00:63:b1:fb\u001a\u0010192.168.122.1/24\n\u001f\n\nvirbr0-nic\u0012\u001152:54:00:63:b1:fb\n,\n\u0006virbr2\u0012\u001152:54:00:bf:d2:5b\u001a\u000f192.168.42.1/24\n\u001f\n\nvirbr2-nic\u0012\u001152:54:00:bf:d2:5b\n+\n\u0007docker0\u0012\u001102:42:29:4d:40:bf\u001a\r172.17.0.1/16:\u0005amd64\"\u0005linux\"\u0003dev\"\u0006server\"\u0008postgres\"\tlocalhost\"\u0003poc(\ufffd\ufffd\ufffd\ufffd\u0005:\u0000Z\u0005agentj\u0008passwordj\u0006passwdj\u0004passj\u0007api_keyj\tapi_tokenj\naccess_keyj\nsecret_keyj\u000bprivate_keyj\u0006secretrM\n\tlocal-poc\u0012\u0003poc\u001a\u001a\n\u000bssh_version\u0012\u000bOpenSSH_7.9\u001a\u0010\n\u0007pumpkin\u0012\u0005spice\u001a\r\n\u0004chia\u0012\u0005lattez\u000e5.14.1#b45811c\u001as\ufffd\u0001junmatched token: template: :1:101: executing \"\" at \u003c.labels.hostname\u003e: map has no entry for key \"hostname\"\ufffd\u0001\u0003\ufffd\u0002\u0000*\u0000","time":"2019-10-29T14:32:12-08:00","type":"event"}
```
