### ISSUE TITLE
The 'sensuctl cluster health' and API '/health' endpoint hang when etcd is configured for SSL

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3423]
## Expected Behavior

I'd expect `sensuctl cluster health` to continue working when SSL is enabled for Etcd.

## Steps to Reproduce (for bugs)

Generated certs:
```
yum install golang-bin
cd /root
git clone https://github.com/cloudflare/cfssl.git
cfssl/
make
export PATH=/root/cfssl/bin:$PATH

# Generate CA

mkdir -p /etc/sensu/etcd-ssl
cd /etc/sensu/etcd-ssl
echo '{"CN":"CA","key":{"algo":"rsa","size":2048}}' | cfssl gencert -initca - | cfssljson -bare ca -
echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json

# Generate certs

export ADDRESS=192.168.52.30,sensu-backend1
export NAME=sensu-backend1
echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="$ADDRESS" -profile=peer - | cfssljson -bare $NAME

export ADDRESS=192.168.52.31,sensu-backend2
export NAME=sensu-backend2
echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="$ADDRESS" -profile=peer - | cfssljson -bare $NAME

export NAME=client
echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="" -profile=client - | cfssljson -bare $NAME
```
Backend config

```
[root@sensu-backend1 ~]# cat /etc/sensu/backend.yml 
---
state-dir: "/var/lib/sensu/sensu-backend"
api-url: https://sensu-backend-peer1.example.com:8080
cert-file: "/etc/sensu/ssl/cert.pem"
key-file: "/etc/sensu/ssl/key.pem"
trusted-ca-file: "/etc/sensu/ssl/ca.crt"
etcd-listen-client-urls: https://0.0.0.0:2379
etcd-advertise-client-urls: https://0.0.0.0:2379
etcd-cert-file: "/etc/sensu/etcd-ssl/sensu-backend1.pem"
etcd-key-file: "/etc/sensu/etcd-ssl/sensu-backend1-key.pem"
etcd-trusted-ca-file: "/etc/sensu/etcd-ssl/ca.pem"
etcd-client-cert-auth: true
```

ERROR:

```
[root@sensu-backend1 ~]# sensuctl cluster health
Error: GET "/health": Get https://sensu-backend1.example.com:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

All other sensuctl commands work. Also a `curl` of the `/health` API hangs. There is nothing in logs that indicates an error.

I know this SSL setup works because I setup another node using same CA and client certs for etcd that were copied from first node and setup Etcd replicator using this config:

```
[root@sensu-backend-peer2 ~]# sensuctl dump federation/v1.EtcdReplicator
type: EtcdReplicator
api_version: federation/v1
metadata:
  name: role_replicator
spec:
  api_version: core/v2
  ca_cert: /etc/sensu/etcd-ssl/ca.pem
  cert: /etc/sensu/etcd-ssl/client.pem
  key: /etc/sensu/etcd-ssl/client-key.pem
  namespace: ""
  replication_interval_seconds: 30
  resource: Role
  url: https://192.168.52.30:2379
```

I created a test `Role` on the 2nd backend and it shows up on 1st backend.

## Context

I am working on the sensu-puppet module to support Etcd replicator and wanted to do it via SSL and seems Etcd SSL isn't fully functional or setup correctly.

CC @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend version 5.15.0, build 13884593ee08a7f25d7f66a8b71da61c529de014, built 2019-11-19T20:18:33Z
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
