### ISSUE TITLE
Allow secrets/env vars to be used in assets

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3619]
As a user who has security restrictions around using external repositories to provide assets, I'd like to have the ability to provide an asset configuration which specifies header information (like tokens or user/password auth) in the form of a secret or an environment variable. Ideally, this would look something like:

```
type: Asset
api_version: core/v2
metadata:
  name: check_cpu_linux_amd64
  namespace: default
  labels:
    origin: bitbucket
spec:
  url: https://bitbucket.corp.com/981307deb10ebf1f1433a80da5504c3c53d5c44f/sensu-go-cpu-check_0.0.3_linux_amd64.tar.gz
  sha512: 487ab34b37da8ce76d2657b62d37b35fbbb240c3546dd463fa0c37dc58a72b786ef0ca396a0a12c8d006ac7fa21923e0e9ae63419a4d56aec41fccb574c1a5d3
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  headers:
    Authorization: Bearer $BITBUCKET_TOKEN
  secrets:
  - BITBUCKET_TOKEN
    secret: bitbucket-token-vault
```
