### ISSUE TITLE
Equal sign in value can not get set in env_vars

### ISSUE THREAD

**Issue by damon1991** [sensu/sensu-go#3691]
## Expected Behavior

When trying to setup a new check with env_vars and a variable contains an equal sign the check should get created properly. (Example env_vars: DOMAIN=DC=EXAMPLE,DC=LOCAL)

## Current Behavior

When I set the variable and try to create the check with sensuctl create -f file.yml (or file.json) I only receive the error:
Error: error putting resource #0 with name "test-check" and namespace "default" (/api/core/v2/namespaces/default/checks/test-check): invalid argument(s) received

## Steps to Reproduce (for bugs)

1. Create a yaml or json file to setup a new check or update an existing one.
2. Insert some env_vars with equal signs in the value.
3. Try to create/update the check with sensuctl

## Context

Example yaml file:

```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: test-check
  namespace: default
spec:
  command: signamus-checks
  env_vars:
  - LDAP=DC=EXAMPLE,DC=LOCAL
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  publish: false
  round_robin: false
  subscriptions:
  - test
  timeout: 60
  ttl: 0
```

## Your Environment

sensuctl version 5.19.1
running on Ubuntu 18.03 installed via repo https://packagecloud.io/sensu/stable/ubuntu/
Sensu backend in docker with version 5.17.2-0
