### ISSUE TITLE
Concatenated YAML does not support CRLF

### ISSUE THREAD

**Issue by mjiderhamn** [sensu/sensu-go#3734]
## Expected Behavior
`sensuctl create -f` with multiple YAML files concatenated into one with `---` delimiter should work the same way whether LF or CRLF line endings are used.

## Current Behavior
`sensuctl create -f` can handle YAML files with either LF or CRLF. If it is a concatenated YAML file however, using CRLF results in only the first resource being processed.

Presumably, [cli/resource/parse.go line 37](https://github.com/sensu/sensu-go/blob/master/cli/resource/parse.go#L37) is the culprit.

## Steps to Reproduce (for bugs)
1. Create file with the following contents with CRLF line endings.
```
type: CheckConfig
api_version: core/v2
metadata:
  name: foo
spec:
  command: echo foo
  interval: 100
---
type: CheckConfig
api_version: core/v2
metadata:
  name: bar
spec:
  command: echo bar
  interval: 200
```
2. Import using `sensuctl create -f`

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.19.2
