### ISSUE TITLE
Add internal filter: is_recovered

### ISSUE THREAD

**Issue by DoctorOgg** [sensu/sensu-go#3747]
for some notification handers, like slack and victorops, I would like to see when an event/alert is recovered, this more closely matches the behavior of classic sensu. Victorops, as well as other notification tools, will stop paging when a recovered event is received. as well as those who are watching in slack would like to know without having to add 
``` 
 - event.check.occurrences == 1 || event.check.occurrences % (3600 / event.check.interval)
```

today I'm using the fatigue_check to help with this.

```yaml 
---
type: EventFilter
api_version: core/v2
metadata:
  name: fatigue_check
  namespace: default
spec:
  action: allow
  expressions:
  - event.check.occurrences == 1 || event.check.occurrences % (3600 / event.check.interval)
    == 0
  runtime_assets:
  - fatigue-filter
```

however, I would love to add the is_recovered at the handler example:

```yaml
---
api_version: core/v2
type: Handler
metadata:
  namespace: default
  name: slack
spec:
  type: pipe
  command: sensu-slack-handler --channel '#sensu' --username 'sensu'
  runtime_assets:
    - sensu/sensu-slack-handler
  filters:
    - is_incident
    - is_recovered
    - not_silenced
    - fatigue_check
  secrets:
    - name: SLACK_WEBHOOK_URL
      secret: slack_webhook_url
  timeout: 10

```
