### ISSUE TITLE
Display information about asset installation failure in the dashboard and prevent check execution. 

### ISSUE THREAD

**Issue by randrusiak** [sensu/sensu-go#3755]
I noticed that there is no explicit warning when the required asset isn't installed on the specific machine. 

It might be logical for experienced users if check result returns "< command > not found" it means that asset wasn't installed. I'm a new user and I waste a lot of time before I found why the check didn't work.

Currently, there is only a single message in sensu-agent which looks like:

`{"asset":"sensu-plugins-postgres","component":"asset-manager","entity":"test-machine","filter":["entity.system.os == 'linux'","entity.system.arch == 'amd64'","entity.system.platform_family == 'debian'","entity.system.platform_version.split('.')[0] == '9'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":"2020-05-14T14:47:02+02:00"}
`
## Feature Suggestion

I think that there should be an explicit warning (label next to asset name) in the sensu dashboard that asset wasn't installed on the machine and the check shouldn't be executed by sensu-agent if some of the required assets are missing. 

## Possible Implementation
None
## Context

I added  [sensu-plugins-postgres](https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-postgres) and I created check with following configuration:

```
type: CheckConfig
api_version: core/v2
metadata:
  name: check-postgres-alive
  namespace: default
spec:
  command: check-postgres-alive.rb -d template1 -f /var/lib/postgresql/.pgpass
  handlers: []
  interval: 60
  publish: true
  runtime_assets:
    - sensu-plugins-postgres
    - sensu-ruby-runtime
  subscriptions:
  - postgres
```
In the dashboard I got following result:
![image](https://user-images.githubusercontent.com/29524175/81940973-7e343480-95f8-11ea-8b95-1fa0811467c6.png)

In this case, sensu-plugins-postgres wasn't installed on the host because this asset doesn't have build for ubuntu.
