### ISSUE TITLE
allow to access labels of _real_ entity from check

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go#3759]
## Feature Suggestion

Providing a way to access labels, or any other attributes, of _real_ entity from check.

## Possible Implementation

provide an attribute of the real entity that can be referenced in check. for example, `.real_entity`. `.real_entiry.labels` returns the `labels` of the real entity, not the proxy entity. 

```yaml
type: CheckConfig
api_version: core/v2
metadata:
  created_by: admin
  name: check_dig
  namespace: default
spec:
  check_hooks: null
  command: '{{ .real_entiry.labels.nagios_plugin_dir }}/check_dig -H {{ .labels.target_host
    }} --query_address={{ .labels.query_address }}'
  env_vars: null
  handlers: []
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: nagios_perfdata
  output_metric_handlers: null
  proxy_entity_name: ""
  proxy_requests:
    entity_attributes:
    - entity.entity_class == 'proxy'
    - entity.labels.proxy_type == 'dig'
    splay: false
    splay_coverage: 0
  publish: true
  round_robin: false
  runtime_assets: null
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
  - proxy
  timeout: 0
  ttl: 0
```

## Context

when you have Linux/i386, amd64, and BSDs, the path to check command directory vary. for example, path to Nagios plugin directory can be one of:

- /usr/lib64/nagios/plugins
- /usr/lib32/nagios/plugins
- /usr/local/libexec/nagios

this is easy to achieve by using labels at agent level.

```yaml
---
type: Entity
api_version: core/v2
metadata:
  labels:
    nagios_plugin_dir: /usr/local/libexec/nagios
  name: target1.i.trombik.org
```

and the check looks like this:

```yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  created_by: admin
  name: check_load
  namespace: default
spec:
  check_hooks: null
  command: '{{ .labels.nagios_plugin_dir }}/check_load -w 1,2,3 -c 2,3,4'
  env_vars: null
  handlers: []
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: nagios_perfdata
  output_metric_handlers: null
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets: null
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
  - system
  timeout: 0
  ttl: 600
```

so far, so good. but when you want to monitor external resources with `proxy` entity, it is not possible.

here is a proxy entity.

```yaml
type: Entity
api_version: core/v2
metadata:
  created_by: admin
  labels:
    proxy_type: dig
    query_address: google.com
    target_host: 8.8.8.8
  name: 8.8.8.8
  namespace: default
spec:
  deregister: false
  deregistration: {}
  entity_class: proxy
  last_seen: 0
  sensu_agent_version: ""
  subscriptions: null
  system:
    cloud_provider: ""
    hostname: 8.8.8.8
    libc_type: ""
    network:
      interfaces: null
    platform: unknown
    vm_role: ""
    vm_system: ""
```
and the check:

```yaml
type: CheckConfig
api_version: core/v2
metadata:
  created_by: admin
  name: check_dig
  namespace: default
spec:
  check_hooks: null
  command: '{{ .labels.nagios_plugin_dir }}/nagios/check_dig -H {{ .labels.target_host
    }} --query_address={{ .labels.query_address }}'
  env_vars: null
  handlers: []
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: nagios_perfdata
  output_metric_handlers: null
  proxy_entity_name: ""
  proxy_requests:
    entity_attributes:
    - entity.entity_class == 'proxy'
    - entity.labels.proxy_type == 'dig'
    splay: false
    splay_coverage: 0
  publish: true
  round_robin: false
  runtime_assets: null
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
  - proxy
  timeout: 0
  ttl: 0
```
because `.labels` refers to the label of the proxy entity, not the entity on which the check is executed.
