### ISSUE TITLE
labels does not support nested key

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go#3778]
## Expected Behavior

when `sensu-go` agent is configured with nested `labels`, you can replace tokens with the nested key and value.

## Current Behavior

an agent has nested key in `labels` (`nginx`).

```yaml
backend-url: ws://172.16.100.254:8081
cache-dir: /var/cache/sensu/sensu-agent
keepalive-critical-timeout: 300
keepalive-warning-timeout: 120
labels:
    nagios_plugin_dir: /usr/local/libexec/nagios
    nginx:
        hostname: target1
    sensu_plugin_dir: /home/sensu/.gem/ruby/2.6/bin
subscriptions:
- system
- web_server
```

but the nested key does not exist in the entity.

```yaml
type: Entity
api_version: core/v2
metadata:
  labels:
    nagios_plugin_dir: /usr/local/libexec/nagios
    nginx: ""
    sensu_plugin_dir: /home/sensu/.gem/ruby/2.6/bin
  name: target1.i.trombik.org
  namespace: default
...
```

## Possible Solution

support nested keys as same as other entity's attibutes.

## Steps to Reproduce (for bugs)

1. configure an agent with nested keys in `labels`
2. show entity info by `sensuctl entity info`

## Context

the doc states that:

> {{ index .labels "cpu.threshold" }} would be replaced with a custom label called cpu.threshold

but it does not work (using `index .labels "nginx.hostname"`)  because the entity does not have it.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.20.0
* Installation method (packages, binaries, docker etc.): [my own package](https://github.com/trombik/freebsd-ports-sensu-go/tree/master/sysutils/sensu-go)
* Operating System and version (e.g. Ubuntu 14.04): FreeBSD 12.1
