### ISSUE TITLE
Checks that use stdin are not given an entity

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3827]
## Expected Behavior
When I write a check that uses the stdin feature, I would expect to receive an event that contains the check request and the entity information.

## Current Behavior
Only the check request object is present.

## Possible Solution
Include the agent entity in the object sent to the check stdin.

## Steps to Reproduce (for bugs)
You can use the following check to observe that only the check request is supplied:
```
type: Check
api_version: core/v2
metadata:
  name: cat_test
  namespace: default
spec:
  command: cat
  interval: 5
  publish: true
  stdin: true
  subscriptions:
  - test
```
