### ISSUE TITLE
Agent fails to log error related to asset download failure

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3863]
## Expected Behavior

Sensu agent log messages are usable for troubleshooting asset download errors.

## Current Behavior

Agent silently fails to download an asset from an intentionally wrong URL.

## Steps to Reproduce (for bugs)
1. Create an asset that shouldn’t work:
```
type: Asset
api_version: core/v2
metadata:
  name: test
spec:
    sha512: cbee19124b7007342ce37ff9dfd4a1dde03beb1e87e61ca2aef606a7ad3c9bd0bba4e53873c07afa5ac46b0861967a9224511b4504dadb1a5e8fb687e9495304
    url: https://this.wont.work/5123017d3dadf2067fa90fc28275b92e9b586885/sensu-ruby-runtime_0.0.10_ruby-2.4.4_centos6_linux_amd64.tar.gz
```
2. Create a check to exercise the asset
```
type: CheckConfig
api_version: core/v2
metadata:
  name: test
spec:
  command: echo test
  interval: 10
  publish: true
  runtime_assets:
  - test
  subscriptions:
  - test
```
3. Configure agent for debug level logging, observe lack of any error on the asset:
```
{"component":"agent","content_type":"application/octet-stream","level":"info","msg":"message received","payload_size":390,"time":"2020-06-25T20:22:02Z","type":"check_request"}
{"component":"agent","level":"info","msg":"scheduling check execution: test","time":"2020-06-25T20:22:02Z"}
{"assets":["test"],"check":"test","component":"agent","level":"debug","msg":"fetching assets for check","namespace":"default","time":"2020-06-25T20:22:02Z"}
{"asset":"test","component":"asset-manager","entity":"testenv","filters":null,"level":"debug","msg":"entity filtered, installing asset","time":"2020-06-25T20:22:02Z"}
{"component":"agent","content_type":"application/octet-stream","level":"info","msg":"sending message","payload_size":749,"time":"2020-06-25T20:22:02Z","type":"event"}
```
4. And of course the asset isn't downloaded: 
```
# ls -la /var/cache/sensu/sensu-agent/
total 10
drwxr-x--- 2 sensu sensu     4 Jun 25 20:27 .
drwxr-xr-x 4 root  root      4 Mar 10 18:33 ..
-rw------- 1 sensu sensu 16384 Jun 25 20:21 assets.db
-rw------- 1 sensu sensu 32768 Jun 25 20:27 queue.db
``` 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.21.0 and tested back to 5.18.2
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by portertech** [comment]
@cwjohnston to test a few other URL cases (e.g. 404) and update this issue.

**Comment by cwjohnston** [comment]
Per request from @echlebek, I have retested with a different asset configuration. In this iteration of the asset I am using a URL which returns a response:

```
type: Asset
api_version: core/v2
metadata:
  name: test
  namespace: default
spec:
  sha512: cbee19124b7007342ce37ff9dfd4a1dde03beb1e87e61ca2aef606a7ad3c9bd0bba4e53873c07afa5ac46b0861967a9224511b4504dadb1a5e8fb687e9495304
  url: https://www.example.com/5123017d3dadf2067fa90fc28275b92e9b586885/sensu-ruby-runtime_0.0.10_ruby-2.4.4_centos6_linux_amd64.tar.gz
```

The agent handles this iteration more like I would expect, in that the agent creates an event with `unknown` severity `error getting assets for event` and indicating sha mismatch. 👍

That said, the agent doesn't log any indication of the error, even at debug log level:

```
{"component":"agent","content_type":"application/octet-stream","level":"info","msg":"message received","payload_size":400,"time":"2020-06-30T18:37:22Z","type":"check_request"}
{"component":"agent","level":"info","msg":"scheduling check execution: test","time":"2020-06-30T18:37:22Z"}
{"assets":["test"],"check":"test","component":"agent","level":"debug","msg":"fetching assets for check","namespace":"default","time":"2020-06-30T18:37:22Z"}
{"asset":"test","component":"asset-manager","entity":"sensu-agent","filters":null,"level":"debug","msg":"entity filtered, installing asset","time":"2020-06-30T18:37:22Z"}
{"component":"agent","content_type":"application/octet-stream","level":"info","msg":"sending message","payload_size":775,"time":"2020-06-30T18:37:22Z","type":"event"}
```

Finally, let's consider the HTTP response for this asset URL. `curl -i curl -i https://www.example.com/5123017d3dadf2067fa90fc28275b92e9b586885/sensu-ruby-runtime_0.0.10_ruby-2.4.4_centos6_linux_amd64.tar.gz` returns an HTTP 404. In my estimation the agent should stop right here and surface the HTTP response.
