### ISSUE TITLE
Proxy entity does not get scheduled on non default namespace

### ISSUE THREAD

**Issue by falmada** [sensu/sensu-go#3874]
When setting up a proxy entity and a check to monitor a website within a namespace other than default, no events come out from this check (even after trying to manually execute it)

## Expected Behavior
When doing the same on default namespace, events start appearing after a minute or and entity is also listed.

## Current Behavior
No events or entities appear listed on any other namespace different than default.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Setup namespace: 
$ sensuctl namespace create test
2. Create testweb.yaml
```
type: CheckConfig
api_version: core/v2
metadata:
  name: check-testweb
  namespace: test
spec:
  command: check-http.rb -u https://www.google.com -r
  interval: 60
  proxy_entity_name: testweb
  publish: true
  round_robin: true
  runtime_assets:
  - sensu-plugins-http
  - sensu-ruby-runtime
  subscriptions:
  - proxy
```
3. Create objects: 
$ sensuctl create --file testweb.yaml
4. Check for events on new namespace
$ sensuctl event list --namespace test
5. Check for entities on new namespace
$ sensuctl entity list --namespace test
6. Execute manual check
$ sensuctl check execute check-testweb --namespace test

## Context
I'm new to Sensu, trying to setup multiple namespace (one per application/environment) to organize the different checks/entities

The logs, even on debug, are not giving much info
Jun 30 13:34:03 linuxvm sensu-backend: {"check":"check-testweb","component":"schedulerd","level":"debug","msg":"sending check request","time":"2020-06-30T13:34:03-07:00","topic":"sensu:check:test:proxy"}

## Your Environment
All agent, sensuctl and backend setup in the same VM. Have a second VM with agent only, but issue appears whether that one is running or not, does not seem to make a difference.

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
$ sensu-backend version
sensu-backend version 5.21.0+ee, enterprise edition, build 081a854d483d7881bbcf4cb60c44f87ea5fdf425, built 2020-06-11T19:45:19Z, built with go1.13.7
$ sensu-agent version
sensu-agent version 5.21.0+ee, enterprise edition, build 081a854d483d7881bbcf4cb60c44f87ea5fdf425, built 2020-06-11T19:48:44Z, built with go1.13.7
$ sensuctl version
sensuctl version 5.21.0+ee, enterprise edition, build 081a854d483d7881bbcf4cb60c44f87ea5fdf425, built 2020-06-11T19:49:27Z, built with go1.13.7

* Installation method (packages, binaries, docker etc.):
packages from repo using yum

* Operating System and version (e.g. Ubuntu 14.04):
OS: Red Hat Enterprise Linux Server release 7.8
