### ISSUE TITLE
sensuctl edit can load invalidly namespaced resources

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#3936]
## Expected Behavior

```
$ sensuctl edit clusterrolebindings cluster-admin
<valid changes>
<resource gets saved>
```

## Current Behavior

```
sensuctl edit clusterrolebindings cluster-admin
<valid changes>
Error: error putting resource #0 with name "cluster-admin" and namespace "default" (/api/core/v2/clusterrolebindings/cluster-admin): resource is invalid: ClusterRoleBinding cannot have a namespace
```

Cluster Role Bindings indeed are not namespaced:
```
$ sensuctl cluster-role-binding info cluster-admin --format yaml
type: ClusterRoleBinding
api_version: core/v2
metadata:
  name: cluster-admin
spec:
  role_ref:
    name: cluster-admin
    type: ClusterRole
  subjects:
  - name: cluster-admins
    type: Group
```

But `sensuctl edit` loads the cluster role binding to be edited with a namespace field in its metadata (it shouldn't be there!), leading to a failure on save if I don't manually remove it:
```
[...]
metadata:
  name: cluster-admin
  namespace: default
[...]

```
## Your Environment

* Sensu version: 6.0.0-rc1
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by calebhailey** [comment]
Confirmed this behavior is unchanged as of 6.2.2. 

On a fresh install (from Docker) the following command:

```
$ sensuctl edit clusterrolebindings cluster-admin
```

opens an editor with the following contents: 

```
type: ClusterRoleBinding
api_version: core/v2
metadata:
  name: cluster-admin
  namespace: default
spec:
  role_ref:
    name: cluster-admin
    type: ClusterRole
  subjects:
  - name: cluster-admins
    type: Group
```
