### ISSUE TITLE
Windows agent doesn't properly handle timeouts

### ISSUE THREAD

**Issue by nicolasbrechet** [sensu/sensu-go#3979]
## Expected Behavior

When setting up a timeout value in a CheckConfig, if the check execution takes longer than the timeout value, I expect the "Execution timed out" to appear after the number of seconds set in the timeout value.

## Current Behavior

Timeout happens when the check ends, not taking into account the timeout value

## Steps to Reproduce (for bugs)

1. Setup a Windows check (Powershell) with a 30s sleep and a 20s timeout
2. Run the check: after a bit more than 30s the "Execution timed out" message appears
3. Setup a Windows check (Powershell) with a 45s sleep and a 20s timeout
4. Run the check: after a bit more than 45s the "Execution timed out" message appears
<img width="1249" alt="sensu-bug-img1" src="https://user-images.githubusercontent.com/1842586/90876194-8d1e4600-e3a2-11ea-8229-edfd20d5d8da.png">
<img width="1233" alt="sensu-bug-img2" src="https://user-images.githubusercontent.com/1842586/90876234-9d362580-e3a2-11ea-86ff-32d113072eac.png">

## Context

Trying to monitor a Windows server using checks https://github.com/sensu/sensu-windows-powershell-checks

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.0.0
* Installation method (packages, binaries, docker etc.): packages for agent and sensuctl, docker for Sensu-backend
* Operating System and version (e.g. Ubuntu 14.04): agent runs on Microsoft Windows Server 2012 R2 Datacenter 6.3.9600 Build 9600, sensuctl on macOs 10.15.6, Sensu-backend runs on Docker19.03.12, build 48a66213fe on Centos 7.8.2003

**Comment by jspaleta** [comment]
Okay I've confirmed this using windows agent 6.2.0

Check has status result of 2, and checkout indicating timeout, but the execution duration matched the sleep duration, _not_ the timeout.

Looks like Agent noticed it timeout'd, but didn't kill the process off at the timeout breach.

### Check definition (yaml)
```
type: CheckConfig
api_version: core/v2
metadata:
  created_by: admin
  name: sleep-test
  namespace: windows-poc
spec:
  check_hooks: null
  command: PowerShell.exe Write-Host "start sleep"; Start-Sleep -s 30 ; Write-Host "sleep done"
  env_vars: null
  handlers: []
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: null
  proxy_entity_name: ""
  publish: false
  round_robin: false
  runtime_assets: null
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
  - windows
  timeout: 10
  ttl: 0
```

### Event Result (json)
```
{
  "check": {
    "command": "PowerShell.exe Write-Host \"start sleep\"; Start-Sleep -s 30 ; Write-Host \"sleep done\"",
    "handlers": [],
    "high_flap_threshold": 0,
    "interval": 60,
    "low_flap_threshold": 0,
    "publish": false,
    "runtime_assets": null,
    "subscriptions": [
      "windows"
    ],
    "proxy_entity_name": "",
    "check_hooks": null,
    "stdin": false,
    "subdue": null,
    "ttl": 0,
    "timeout": 10,
    "round_robin": false,
    "duration": 30.3260258,
    "executed": 1615323146,
    "history": [
      {
        "status": 0,
        "executed": 1615322632
      },
      {
        "status": 2,
        "executed": 1615322673
      },
      {
        "status": 2,
        "executed": 1615323146
      }
    ],
    "issued": 1615323146,
    "output": "Execution timed out\n",
    "state": "failing",
    "status": 2,
    "total_state_change": 0,
    "last_ok": 1615322632,
    "occurrences": 2,
    "occurrences_watermark": 2,
    "output_metric_format": "",
    "output_metric_handlers": null,
    "env_vars": null,
    "metadata": {
      "name": "sleep-test",
      "namespace": "windows-poc"
    },
    "secrets": null,
    "is_silenced": false,
    "scheduler": ""
  },
  "entity": {
    "entity_class": "agent",
    "system": {
      "hostname": "EC2AMAZ-94B5HPE",
      "os": "windows",
      "platform": "Microsoft Windows Server 2019 Datacenter",
      "platform_family": "Server",
      "platform_version": "10.0.17763 Build 17763",
      "network": {
        "interfaces": [
          {
            "name": "Ethernet",
            "mac": "06:9f:1c:9c:8a:11",
            "addresses": [
              "fe80::5d3b:9645:2ece:ec82/64",
              "10.0.0.96/24"
            ]
          },
          {
            "name": "Loopback Pseudo-Interface 1",
            "addresses": [
              "::1/128",
              "127.0.0.1/8"
            ]
          }
        ]
      },
      "arch": "amd64",
      "libc_type": "",
      "vm_system": "",
      "vm_role": "",
      "cloud_provider": "",
      "processes": null
    },
    "subscriptions": [
      "windows",
      "disks",
      "entity:windows-demo"
    ],
    "last_seen": 1615323146,
    "deregister": false,
    "deregistration": {},
    "user": "agent",
    "redact": [
      "password",
      "passwd",
      "pass",
      "api_key",
      "api_token",
      "access_key",
      "secret_key",
      "private_key",
      "secret"
    ],
    "metadata": {
      "name": "windows-demo",
      "namespace": "windows-poc"
    },
    "sensu_agent_version": "6.2.0"
  },
  "id": "47824b40-649e-42fc-b38e-8b40cee479e4",
  "metadata": {
    "namespace": "windows-poc"
  },
  "sequence": 4,
  "timestamp": 1615323176
}
```
