### ISSUE TITLE
Round-robin proxy check scheduling is inconsistent around restarts

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4013]
## Expected Behavior
Agent restarts are minimally disruptive to proxy check scheduling.

## Current Behavior
Agent restarts can result in proxy check scheduling being unstable for a large amount of time. In one user's case, it took up to 30 minutes for the schedule to stabilize after a rolling restart of the agents.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Create a cluster with several hundred agents.
2. Schedule round robin proxy checks to run on the agents.
3. Observe the schedule being inconsistent.

## Context
Reported by a customer.

**Comment by portertech** [comment]
We need to do some deep investigative work here. It's a complex issue.

**Comment by portertech** [comment]
I'll schedule a discussion later this week for the team to discuss this issue.

**Comment by mcbsd** [comment]
Hi,

just to share that we are facing this issue for very long time. Below is screenshot of 3 sensu backend nodes where one of them is always over utilized compare to other two where load is distributed more evenly. Some time when the load was too high on single node, we stopped the agent who schedules checks on behalf of proxy entities, then started after a while and the load was distributed more evenly. The sharp drop on the screenshot represents reload of checks where we restart sensu agents and our polling backend on server nodes as part of the reload.
We have 340 proxy entities and 70 proxy checks with splay 90. 

![image](https://user-images.githubusercontent.com/64481947/97678635-6e1fec80-1a94-11eb-868f-1db0074ac859.png)

**Comment by jsnod** [comment]
Just experienced this last night and spent hours trying to figure out why checks weren't triggering.  Proxy checks would all fail with the following:

```json
{
    "component": "schedulerd",
    "level": "error",
    "msg": "check not published, no matching entities for proxy request",
    "name": "check-ecs-service-health",
    "namespace": "default",
    "scheduler_type": "round-robin interval",
    "time": "2020-12-15T23:37:30Z"
}
```

I was able to work around this by setting `round_robin: false` on the check. With `round_robin` off they all started working.

**Comment by echlebek** [comment]
@jsnod this is a different problem from the issue. You're encountering expected behaviour, because you asked for round robin scheduling, but your check didn't match any proxy entities for publishing.

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/checks/#round-robin-checks

**Comment by jsnod** [comment]
@echlebek Perhaps, but I experienced this same issue described by OP until I disabled round_robin. Maybe it's a red herring, but in what situation would a check not match any proxy entities? I have a very simple setup: 1 agent, a couple of checks subscribed to it, and a couple of proxy entities. I'm expecting every check to execute against every one of my entities on my single agent. After restarting my agent, a handful of checks would not execute and I saw a bunch of the above errors.  After some time (30ish min?) they'd all eventually work as described by the OP. But with round_robin off they trigger immediately after agent restart. Might be coincidence but they seem related to me.

**Comment by echlebek** [comment]
@jsnod I see, perhaps it is related after all then. Can you share your check and entity configuration, for reference?

**Comment by jsnod** [comment]
@echlebek Entity/Check config is below.  Also a question I had, does `round_robin` work if you only have 1 agent?

Entity:

```
---
type: Entity
api_version: core/v2
metadata:
  name: my-service
  namespace: default
  labels:
    proxy_type: ecs
    environment: prod
    service_name: my-service
    health_url: https://my-service.com/health
spec:
  entity_class: proxy
```

Check:

```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-alb-target-group-health-prod
  namespace: default
spec:
  command: check-alb-target-group-health.rb -t {{ .labels.environment }}-{{ .labels.service_name }}
  handlers:
  - email
  - slack
  interval: 120
  proxy_requests:
    entity_attributes:
    - entity.entity_class == 'proxy'
    - entity.labels.proxy_type == 'ecs'
    - entity.labels.environment == 'prod'
  publish: true
  round_robin: false
  runtime_assets:
  - sensu-plugins-aws
  - sensu-ruby-runtime
  subscriptions:
  - proxy_prod
```
