### ISSUE TITLE
Entity can be listed, but not queried directly

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4062]
The following entity was created with `sensuctl create`. It can be seen in the output of `sensuctl entity list`, but cannot be queried with `sensuctl entity info`.

```
type: Entity
metadata:
  name: sally
  namespace: default
spec:
  entity_class: agent
```
