### ISSUE TITLE
sensuctl prune produces inscrutable errors when specifying type 'hook' instead of 'hooks'

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4142]
## Expected Behavior

Specifying an invalid type for a prune operation will produce a clear error.

## Current Behavior

Running `sensuctl prune hook ...` produces an error which doesn't help an operator understand their mistake.

## Steps to Reproduce (for bugs)
1. Create a hook
```
type: HookConfig
api_version: core/v2
metadata:
  annotations: null
  labels: null
  name: process_tree
  namespace: default
spec:
  command: ps aux
  stdin: false
  timeout: 60
  runtime_assets: null
```
2. Create an empty directory, I'll call mine `empty`
3. Try to delete all hook resources using prune, not realizing that prune expects `hooks` instead of `hook`
```
$ sensuctl prune hook -f empty/ -a
Error: error pruning resources (/api/enterprise/prune/v1alpha): error: code = 0 desc = could not decode the key /sensu.io/hooks/: proto: illegal wireType 7
```
4. Feel confusion inside.
5. Try again, specifying type `hooks` or `core/v2.HookConfig` instead, which seem to work fine.

## Context

The `illegal wireType` error is not very actionable. Can we give a more meaningful error?

Can we support singular forms as well as plural forms in more places? In my experience folks don't readily recall when to use the singular form (e.g. `sensuctl check create`) vs the plural form short names provided by `describe-type` and used by prune, dump, etc.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.2.0
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):
