### ISSUE TITLE
Entity registration events are not fired when entities are created via API

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#4155]
## Expected Behavior

As a Sensu user, I would expect entity registration events to be fired for entities created via the API.

## Current Behavior

Entity registration events are not fired when entities are created via the API.

## Possible Solution

A quick fix would be to export the `createRegistrationEvent` function in keepalived, implement the logic in apid to call the function if the entity doesn't already exist in the store.

We may want to consider a more thorough approach of decoupling entity registration & keepalives by creating a new registrationd/entityd daemon to be used wherever entity registration occurs.

## Steps to Reproduce (for bugs)

1. Create the following resources:
  ```
---
type: Handler
api_version: core/v2
metadata:
  name: registration
spec:
  type: pipe
  command: tee -a /tmp/registration
---
type: Entity
api_version: core/v2
metadata:
  name: test-entity
spec:
  deregister: false
  deregistration: {}
  entity_class: agent
  subscriptions:
    - all
```
2. Notice that `/tmp/registration` doesn't exist.
