### ISSUE TITLE
Dynamic runtime asset paths resolution not working properly

### ISSUE THREAD

**Issue by neuwolferl** [sensu/sensu-go#4184]
## Expected Behavior
The current path of the cached copy of an asset, downloaded on the agent machine, should be resolved by $ASSET_NAME_PATH variable and/or ${{assetPath "asset-name"}} in check command.
## Current Behavior
Apparently the variable and the token expressions are resolved only on Linux and not on Windows.
Note: the asset is fully downloaded and inflated on the target agent machine, I can see the folder with all its content in the agent cache directory.
## Possible Solution
No clue

## Steps to Reproduce (for bugs)
Define and create a check via yaml file which includes and asset in **runtime_assets** fields. Say the asset is called sensu-processes-check. Set as check command:

- ls $SENSU_PROCESSES_CHECK_PATH for a check that will run on linux machines
- dir $SENSU_PROCESSES_CHECK_PATH or powershell -command "ls $SENSU_PROCESSES_CHECK_PATH" for a check that will run on windows machines

On linux the check is executed and correctly outputs the content of the asset folder (e.g. bin directory, README, etc).
On windows it outputs the content of C:\windows\system32.

## Context
Sample check def:
`---
type: CheckConfig
api_version: core/v2
metadata:
  name: Check_Test
  namespace: something
spec:

  command: ls $SENSU_PROCESSES_CHECK_PATH
  publish: true
  interval: 30
  timeout: 60
  subscriptions:
  - something
  runtime_assets:
  - sensu-processes-check
`
## Your Environment

* Sensu version used: 
sensuctl version 6.2.2+ee, enterprise edition, build f269b86dd1ce5ac9eddc9cec5f3e1cc27b6d5988, built 2021-01-14T17:58:28Z, built with go1.13.15
sensu-backend version 6.2.2+ee, enterprise edition, build f269b86dd1ce5ac9eddc9cec5f3e1cc27b6d5988, built 2021-01-14T17:58:28Z, built with go1.13.15
sensu-agent version 6.2.3+ee, enterprise edition, build 56c4e71fe0b3c27fa8e622c4f56af9562e42651e, built 2021-01-20T23:41:47Z, built with go1.13.15
* Installation method (packages, binaries, docker etc.):
The exact steps indicated in the "Deploy Sensu".
* Operating System and version (e.g. Ubuntu 14.04):
Backend is on an Amazon Linux, the linux agent is on the same machine, the windows agent is on a Microsoft Windows 10 Pro 10.0.18363

**Comment by jspaleta** [comment]
I think windows asset path environment variable is working. I think the issue is, depending on which Windows environment you are using, the way the asset path is accessed changes.  This might be a documentation bug?

The problem is, its now possible/reasonable to have several shell environments on windows, each with their own syntax for accessing env vars (ex: github actions windows provides windows console, powershell and bash)

For example:
For the default windows console, you access an environment variable with `%VAR_NAME%`
For powershell, you access an environment variable with `$env:` prefix

In the non-working example above, the windows environment is the default windows console, but the check command is written as if it were posix shell environment

#### Working Windows Shell Example
```
type: Check
api_version: core/v2
metadata:
  name: test_asset_path
  namespace: windows-poc
spec:
  command: echo %SENSU_SENSU_WINDOWS_POWERSHELL_CHECKS_PATH%  %{{assetPath "sensu/sensu-windows-powershell-checks"}}%
  publish: false
  runtime_assets:
  - sensu/sensu-windows-powershell-checks
  subscriptions:
  - windows
  timeout: 10
```

#### Working Windows PowerShell Example
```
type: CheckConfig
api_version: core/v2
metadata:
  name: test_asset_path
  namespace: windows-poc
spec:
  command: powershell -command "echo $env:SENSU_SENSU_WINDOWS_POWERSHELL_CHECKS_PATH  $env:{{assetPath "sensu/sensu-windows-powershell-checks"}}"
  runtime_assets:
  - sensu/sensu-windows-powershell-checks
  subscriptions:
  - windows
  timeout: 10
```
