### ISSUE TITLE
Check did not write to STDOUT

### ISSUE THREAD

**Issue by edgan** [sensu/sensu-go#4204]
It seems to coincide with the restart of the sensu-agent. My guess is the check was in the middle of it's execution when the restart of the agent killed it. This triggered undesired alert.

  Our sensu is managed by Salt, a configuration management tool. I had just made a configuration change to remove a subscription from the /etc/sensu/agent.yml. Salt is configured to auto restart the sensu-agent services on the configuration change. It would be doing this with a `service sensu-agent restart` or `systemctl restart sensu-agent.service`.
  
  It seems like sensu-agent could have a more graceful restart where it finishes what it was doing before restarting instead of just shooting the check in the head.

```
Check did not write to STDOUT
status 4294967295
```

```
ii  sensu-go-agent                         6.2.3-3986                                      amd64        Sensu Go Agent
```

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

```
cat /proc/version
Linux version 4.15.0-128-generic (buildd@lcy01-amd64-025) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020
```

```
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_debian9_linux_amd64.tar.gz     76bcad9  
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_debian_linux_amd64.tar.gz      0f484a7  
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_centos7_linux_amd64.tar.gz     1c10dda  
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_centos6_linux_amd64.tar.gz     0e5b14a  
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_centos_linux_amd64.tar.gz      649e15d  
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_alpine3.8_linux_amd64.tar.gz   a2e67c6  
  sensu-plugins-process-checks   //assets.bonsai.sensu.io/.../sensu-plugins-process-checks_4.1.0_alpine_linux_amd64.tar.gz      67c6b4d  
```

```
type: CheckConfig
api_version: core/v2
metadata:
  created_by: admin
  labels:
    environment: inf
    schedule: 0-23-7
    sensu.io/managed_by: sensuctl
  name: check-process-jenkins-master
  namespace: default
spec:
  check_hooks: null
  command: check-process.rb -p jenkins.war
  env_vars: null
  handlers:
  - opsgenie-allow-check-inf-0-23-7
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: null
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets:
  - sensu-plugins-process-checks
  - sensu-ruby-runtime
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
  - jenkins-master
  timeout: 60
  ttl: 7200
```
