### ISSUE TITLE
Sensuctl create terminates yml after an invalid section

### ISSUE THREAD

**Issue by mariano-dm** [sensu/sensu-go#4242]
When running sensuctl create, if one of the resources cannot be created, it stops processing the file

example 

````
---
type: CheckConfig
api_version: core/v2
metadata:
  name: "sample-all-runners-sample01"
  namespace: some-invalid-namespace

spec:
  command: rb-test-check.sh
  interval: 60
  proxy_entity_name: runner
  publish: False
  round_robin: False
  handlers:
  subscriptions:
    - runner-poc
---
type: CheckConfig
api_version: core/v2
metadata:
  name: "sample-all-runners-sample02"
  namespace: poc
spec:
  command: rb-test-check.sh
  interval: 60
  proxy_entity_name: runner
  publish: False
  round_robin: False
  handlers:
  subscriptions:
    - runner-poc
---

````

the second check won't be created.

## Feature Suggestion

add a --skip-invalid-resources or --force option to move to next --- section instead of exiting

## Context
I have a big yml to publish on CI/CD , every time there is an invalid check that passes basic validation, it stops the rest of checks from publish
