### ISSUE TITLE
Error fetching assets on MacOS agent

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4262]
## Expected Behavior

MacOS agent can fetch, verify, and unpack assets into the asset cache directory. 

## Current Behavior

MacOS agent produces errors fetching assets with an error that suggests the root cause is either a certificate trust issue (perhaps related to [updated requirements for certificate trust in MacOS 10.15+](https://support.apple.com/en-us/HT210176)), or an issues with write permissions for a temp directory (perhaps related to [MacOS "System Integrity Protection"??](https://support.apple.com/en-us/HT204899)). 

Here's the error message: 

```
error getting assets for check: error fetching asset: Get https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_darwin_amd64.tar.gz: x509: failed to load system roots and no roots provided; mkdir /var/folders/1b/qbhk90td1w58p14q7h14pknc0000gn/T/x509trustpolicy637512061: permission denied
```

On the same system I am able to fetch the asset using curl without a certificate error: 

<img width="1002" alt="Screen Shot 2021-04-09 at 12 17 41 PM" src="https://user-images.githubusercontent.com/141373/114230109-978b5100-992d-11eb-991a-b8120fde2638.png">

I observed this error on three different machines today, with MacOS version 10.15.7 (Intel), 11.2.2 (Apple Silicon), and 11.2.3 (Intel). All three were running using a MacOS service account configured as follows: 

```shell
sudo dscl . -create /Groups/_sensu gid 7678
sudo dscl . -create /Groups/_sensu RealName "Sensu Go service group"
sudo dscl . -create /Groups/_sensu passwd "*"
sudo dscl . -create /Users/_sensu
sudo dscl . -create /Users/_sensu uid 7678
sudo dscl . -create /Users/_sensu gid 7678
sudo dscl . -create /Users/_sensu NFSHomeDirectory /opt/sensu
sudo dscl . -create /Users/_sensu UserShell /bin/bash
sudo dscl . -create /Users/_sensu RealName "Sensu Go service account"
sudo dscl . -create /Users/_sensu passwd "*"
sudo mkdir -p /opt/sensu
sudo chown -R _sensu:_sensu /opt/sensu
```

All three agents were run with the following configuration flags (specifically including setting `--cache-dir` to avoid conflicts related to [SIP](https://support.apple.com/en-us/HT204899).

```shell
sudo -E -u _sensu sensu-agent start \
--name workshop \
--backend-url ${SENSU_BACKEND_URL} \
--namespace ${SENSU_NAMESPACE} \
--subscriptions system/macos,workshop \
--deregister true \
--cache-dir /opt/sensu/sensu-agent/cache \
--user ${SENSU_USER} \
--password ${SENSU_PASSWORD}
```

## Possible Solution

It's unclear if the issue at hand is a system/agent certificate configuration issue, or a operating system user / service account permission issue, or both. If it's a permissions issue (writing to a SIP-protected path), perhaps we need a configuration flag for `--asset-temp-dir` in addition to `--cache-dir`? Otherwise it seems we don't have enough control to avoid conflicts with SIP on MacOS.

## Steps to Reproduce (for bugs)

1. Start an agent on MacOS w/ the `system/macos` subscription.
2. Create a check from the following template: 

   ```yaml
   ---
   type: CheckConfig
   api_version: core/v2
   metadata:
     name: disk
   spec:
     command: check-disk-usage --warning {{ .annotations.disk_usage_warning_threshold | default "80.0" }} --critical {{ .annotations.disk_usage_critical_threshold | default "90.0" }}
     runtime_assets:
     - sensu/check-disk-usage:0.4.2
     publish: true
     interval: 30
     subscriptions:
     - system/macos
     - system/macos/disk
     - system/windows
     - system/windows/disk
     - system/linux
     - system/linux/disk
     timeout: 10
     ttl: 0
     handlers: []
   ---
   type: Asset
   api_version: core/v2
   metadata:
     name: sensu/check-disk-usage:0.4.2
     annotations:
       io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/check-disk-usage
       io.sensu.bonsai.name: check-disk-usage
       io.sensu.bonsai.namespace: sensu
       io.sensu.bonsai.tags: ""
       io.sensu.bonsai.tier: Community
       io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/check-disk-usage
       io.sensu.bonsai.version: 0.4.2
   spec:
     builds:
     - filters:
       - entity.system.os == 'windows'
       - entity.system.arch == 'amd64'
       sha512: f51438114cdace9d24ad0171b97fb16a1d3c6377d4cf4b990ab4f2732028cf33c0700ef1f1d266252d0f1bc1564d8197c9743c038f3dcf20f99e8ff711babf5e
       url: https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_windows_amd64.tar.gz
     - filters:
       - entity.system.os == 'darwin'
       - entity.system.arch == 'amd64'
       sha512: 89477eded109c47b6ccf783b1e1be388a1859b7ac591867f9e2a60f0cc5508a2495bb425864dfd230ba867be58da9ec4087635f79ad57314b7756be72830e9b7
       url: https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_darwin_amd64.tar.gz
     - filters:
       - entity.system.os == 'linux'
       - entity.system.arch == 'armv7'
       sha512: 9f626a38af27280681c77d634e47a5283baa8620134bf2ebb7cc7d0d5c3ed52b3403f21cf0907b298aa1d892e885ab8858987b0536e02003d2c6f4f59edff648
       url: https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_linux_armv7.tar.gz
     - filters:
       - entity.system.os == 'linux'
       - entity.system.arch == 'arm64'
       sha512: 0c042d697c27a7287a8091416a629720fedec600416630137841c359b8718d7ae600747b6cbfa983175d7456131f23c64f4b6b759c7367d0d6e5363078130c6a
       url: https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_linux_arm64.tar.gz
     - filters:
       - entity.system.os == 'linux'
       - entity.system.arch == '386'
       sha512: 964b8c133b333d3c3e8b25ea7e17194d256979de7a6adc756285c9f37e1d72f6f1f52a1ddce07198a3751c9e9469f39d62476809286f2bfe6cda57ee89a28305
       url: https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_linux_386.tar.gz
     - filters:
       - entity.system.os == 'linux'
       - entity.system.arch == 'amd64'
       sha512: 1dde2ae2acc342d0362a986e7f52a60ee8599d36072cf6138d1c7edd69631d6e46a7e9a2715df4fe545a9c49c4d354325cdb1cafd7a0c48a03c55c447ca77de6
       url: https://assets.bonsai.sensu.io/228613a4308320a8983fe133140a74bcce35dfa9/check-disk-usage_0.4.2_linux_amd64.tar.gz
   ```

3. :boom: 

## Context

Giving the MacOS agent install guide some ❤️ 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.2.7
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS 10.15.7 (Intel), 11.2.2 (Apple Silicon), 11.2.3 (Intel)
