### ISSUE TITLE
New core/v2.Pipeline resource, Store & HTTP API

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4352]
## Feature Suggestion

Add support for a new Pipeline resource (OSS) for configuring event processing "workflows" including: sets of filters + mutator + handler configuration options. All pipeline primitive (e.g. handler) references require an API version and resource type, this allows a pipeline to reference a commercial handler resource type (i.e. “TCPStreamHandler”). The Pipeline resource is intended to eventually [replace "Set Handlers" (core/v2.Handler.Spec.Type = "set")](https://gist.github.com/calebhailey/1b628fbbcfe5d850abb673fa14bd9380), and add support for a more flexible references to new handler types (i.e. instead of trying to wedge forthcoming `TCPStreamHandler` references into `core/v2.CheckConfig.Spec.Handlers` (a string slice field), we will add a new `core/v2.CheckConfig.Spec` field called `Pipelines` (see below for more information). 

## Possible Implementation

```yaml
---
type: Pipeline
api_version: core/v2 
metadata:
  name: ops
spec:
  workflows:
  - name: elastic
    filters:
    - api_version: core/v2
      name: is_incident 
    - api_version: core/v2
      name: state_change_only 
    mutator:
      api_version: core/v2
      name: add_labels
    handler:
      api_version: commercial/v1
      type: TCPStreamHandler
      name: logstash
```

## Context

Proposal: https://docs.google.com/document/d/1rWDJoSFhpXRe9PUB8i7SVNA_eggJ6v5L8nJB7UaEkKc/edit#
