### ISSUE TITLE
New core/v2.CheckConfig.Spec.Pipelines field

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4353]
## Feature Suggestion

Add support for referencing the new core/v3.Pipeline resources (see: #4352) from check configurations. 

## Possible Implementation

```yaml
---
type: CheckConfig
api_version: core/v2 
metadata:
  name: example
spec:
  command: >- 
    dosomething.sh
  runtime_assets: []
  timeout: 5
  handlers: [] 
  # new "pipelines" field 
  pipelines:
  - api_version: core/v3
    name: elastic
  ...: ...
```

## Context

Proposal: https://docs.google.com/document/d/1rWDJoSFhpXRe9PUB8i7SVNA_eggJ6v5L8nJB7UaEkKc/edit#
