### ISSUE TITLE
Add support for new Javascript Mutators

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4354]
## Feature Suggestion

Support javascript mutators. Add a new string field to the OSS mutator resource type, `core/v2.Mutator.Spec.Type` with a default value of "pipe" (matching `core/v2.Handler.Spec.Type`). Add an OSS built-in mutator type to the `pipeline` package, "javascript", using the [Otto VM](https://github.com/robertkrimen/otto) for event data manipulation. Users can now use javascript to efficiently mutate Sensu Go event data. 

## Possible Implementation

Otto VM should be seeded with a single variable: `event`, which should contain a deserialized event object (a valid `core/v2.Event`). The `eval` should end with a return statement (the returned value should be a string), otherwise the default return value is `JSON.stringify(event)`. The Otto VM should be seeded with a single variable: `event`, which should contain a deserialized event object (a valid `core/v2.Event`). The `eval` should end with a return statement (the returned value should be a string), otherwise the default return value is `JSON.stringify(event)`. Otto VM errors – including errors raised in the eval statement (e.g. try/catch statements) will result in a failed mutation, terminating the mutator's pipeline execution. Otto VM errors should be logged by the Sensu Backend.

```yaml
---
type: Mutator
api_version: core/v2
metadata:
  name: example
spec:
  type: javascript
  eval: |
    var mutatedEvent = {};
    # do mutation here…
    return mutatedEvent; 
```

## Context

Proposal: https://docs.google.com/document/d/1rWDJoSFhpXRe9PUB8i7SVNA_eggJ6v5L8nJB7UaEkKc/edit#
