### ISSUE TITLE
Timezone support in checks not working

### ISSUE THREAD

**Issue by andrew-pickin-epi** [sensu/sensu-go#4385]
Including CRON-TZ or TZ in cron specification is rejected as invalid. 

## Expected Behavior
https://github.com/sensu/sensu-go/pull/3395 
Suggests that `CRON_TZ=Asia/Tokyo 0 * * * *` is valid. However this is rejected as invalid.

## Current Behavior
Specifying TZ or CRON_TZ in cron is rejected.

## Possible Solution
See 3395 above

## Steps to Reproduce (for bugs)
See Above

## Context
Servers run as UTC. Checks required for real-world events that happen in localtime.

## Your Environment
Docker image sensu/sensu:6.2.5
AWS Linux 2

**Comment by calebhailey** [comment]
Just verified that [the examples in our docs](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/checks/#example-cron-checks) are not accepted in version 6.4.0, and there's not much of an explanation in the logs: 

```
{"component":"apid","duration":"2.439ms","level":"info","method":"PUT","msg":"request completed","path":"/api/core/v2/namespaces/default/checks/cron_test","size":72,"status":400,"time":"2021-08-17T21:30:20Z","u
ser":"sensu"}
```

To be more specific, I tried both of the following configuration templates: 

```yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  name: cron_test
spec:
  command: "true"
  cron: 'CRON_TZ=Asia/Tokyo * * * * *'
  handlers: []
  publish: true
  subscriptions:
  - system/linux
---
type: CheckConfig
api_version: core/v2
metadata:
  name: cron_test
spec:
  command: "true"
  cron: 'TZ=Asia/Tokyo * * * * *'
  handlers: []
  publish: true
  subscriptions:
  - system/linux
```

I get the following output: 

```
$ sensuctl create -f 4385.yaml
Error: error putting resource #0 with name "cron_test" and namespace "default" (/api/core/v2/namespaces/default/checks/cron_test): resource is invalid: check cron string is invalid         
```
