### ISSUE TITLE
sensuctl create validation ignores unknown fields at the root level of a resource

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4392]
## Expected Behavior

Attempting to `sensuctl create -f filename.yaml` on a file with an unknown field should result in a validation error. 

## Current Behavior

Sensuctl appears to ignore errant fields in a configuration resource. 

_Pseudo_ Example

```yaml
type: Handler
api_version: core/v2
metadata:
  name: example
spec: 
  type: pipe
  command: echo "hello world"
this_is_not_a_field: true
```

Attempting to `sensuctl create -f` does not result in an error. 

## Possible Solution

Raise an error if a Sensu resource contains unsupported fields. 

## Steps to Reproduce (for bugs)

1. Create a Handler resource like the example provided above with the filename `example.yaml`
2. `sensuctl create -f example.yaml` 
3. 🤷 

## Context

Failing to raise errors for errant resource definitions may lead to unexpected behaviors (e.g. a trainee experienced an issue with the Sensu Go Workshop that they spent a fair amount of time troubleshooting, and it turned out that they had incorrectly indented the `secret` field in a handler). 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):6.4.0
* Installation method (packages, binaries, docker etc.): Docker
* Operating System and version (e.g. Ubuntu 14.04): Alpine (official Docker container image)
