### ISSUE TITLE
Assets defined in check spec don't show up in the UI

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#4497]
## Expected Behavior

When specifying an asset as part of a check specification, I should see the asset listed in the UI regardless of whether or not the asset is added/downloaded.

## Current Behavior

Currently, I have a check defined as the following:
```yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  annotations:
    fatigue_check/allow_resolution: "false"
    fatigue_check/interval: "1800"
    fatigue_check/occurrences: "3"
    fatigue_check/suppress_flapping: "true"
  created_by: admin
  labels:
    contacts: linux
    sensu.io/managed_by: sensuctl
  name: check-disk-usage
  namespace: default
spec:
  check_hooks: null
  command: check-disk-usage.rb 
  env_vars: null
  handlers:
  - email
  high_flap_threshold: 60
  interval: 900
  low_flap_threshold: 20
  output_metric_format: ""
  output_metric_handlers:
  - influx-db
  pipelines: []
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets:
  - sensu-plugins/sensu-plugins-disk-checks
  - sensu/sensu-ruby-runtime
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
  - linux
  timeout: 0
  ttl: 0

```
Which clearly indicates that the check depends on 2 assets:

* Ruby runtime
* disk checks

However, I've only added one of them to the backend (the Ruby runtime). Yet, the check definition in the UI *only* displays the asset that is currently downloaded, leading Sensu operators to the conclusion that the check spec differs from what's being displayed in the UI. 

<img width="1216" alt="CleanShot 2021-11-16 at 20 30 29" src="https://user-images.githubusercontent.com/898627/142093645-e7da1ab5-3745-49d6-a3cd-f158c4d7a691.png">

## Possible Solution

IMHO the solution here is to make the UI consistent with the check spec and better surface the fact that an asset couldn't be downloaded in the UI. Further, surfacing the reason why the asset couldn't be downloaded would go a long way in helping operators better understand what's going on, rather than poring over logs.

## Steps to Reproduce (for bugs)

1. Create a check with the ruby runtime asset and another ruby check as a dependency
2. Only add the ruby runtime through the UI
3. Observe that the UI only displays the downloaded asset as part of the check configuration summary
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.5
* Installation method (packages, binaries, docker etc.): deb package
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 20.04
