### ISSUE TITLE
Update core/v2.CheckConfig to support new metric threshold evaluation config

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4533]
Proposal: https://github.com/sensu/sensu-go/issues/4486 

## Add new `MetricThreshold`, `MetricThresholdTags`, and `MetricThresholdRule` types 

Add a new `MetricThreshold`, `MetricThresholdTags`, and `MetricThresholdRule` types, used to construct metric threshold expressions.
Metric thresholds should allow users to configure thresholds using the following fields:

Pseudo code example: 

```golang
type MetricThresholdRule struct {
  Min string `json:"min,omitempty"`
  Max string `json:"max,omitempty"`
  Status int `json:"status"`
  NullStatus int `json:"null_status"`
}
type MetricThresholdTags struct {
  Name string `json:"name"`
  Value string `json:"value"`
}
type MetricThreshold struct {
  Name string `json:"name"`
  Tags []MetricThresholdTags `json:"tags,omitempty"`
  Thresholds []MetricThresholdRule `json:"thresholds"`
}
```

* **MetricThreshold.Name**: required, string. Name of the measurement to evaluate (matched against `event.metrics.points[].name` values)
* **MetricThreshold.Tags**: optional. Measurement tags to match (matched against `event.metrics.points[].tags.[]` values)
* **MetricThreshold.Thresholds**: metric threshold rules to apply
  - **MetricThresholdRule.Min**: optional, string. Should be able to `strconv.ParseFloat()` this value and compare with the matching `event.metrics.points` value. See proposal for more information about error handling. 
  - **MetricThresholdRule.Max**: optional, string. Should be able to `strconv.ParseFloat()` this value and compare with the matching `event.metrics.points` value. See proposal for more information about error handling. 
  - **MetricThresholdRule.Status**: required, integer. Used to set `Event.Check.Status` if the expression is true (e.g. 0=OK, 1=WARNING, 2=CRITICAL). 
  - **MetricThresholdRule.NullStatus**: optional, integer (default=0). Used to set `Event.Check.Status` if the measurement is missing. 

_NOTE: threshold values should be `string` type to allow for variable substitution with [Sensu Tokens](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/tokens/#example-token-substitution-for-check-thresholds)._

## Add a new `CheckConfig.Spec.output_metric_thresholds` field

Add a new `CheckConfig.Spec.output_metric_thresholds` field, enabling users to configure one or more metric thresholds (i.e. `[]MetricThresholdRule{}`) with multiple thresholds per metric (e.g. min+max, or min-warning + max-warning + min-critical + max-critical). 

**Example**

```yaml
---
# Example template to fetch host metrics from node_exporter and alert on gauges
type: CheckConfig
api_version: core/v2
metadata:
  name: node_exporter
spec:
  command: wget -q -O- http://127.0.0.1:9100/metrics
  ...: ...
  output_metric_format: prometheus_text
  output_metric_thresholds: 
  - name: system_cpu_used
    tags:
    - name: cpu
      value: cpu-total
    thresholds:
    - max: ”0.7”
      status: 1
    - max: 0.95
      status: 2
  - name: system_mem_free
    thresholds:
    - min: "1024000000"
      status: 2
    - max: "512000000"
      status: 1
```

## Type Validation 

A `CheckConfig` containing `metric_thresholds` configuration is valid when each of the provided thresholds pass the following validation logic: 

* `MetricThreshold.Name` is required (this is the measurement name; i.e. `event.metrics.points` name)
* `MetricThreshold.Thresholds` must not be null 
* Each `MetricThresholdRule` (i.e. each `MetricThreshold.Thresholds` object) must: 
  * One `MetricThresholdRule.Min` or `MetricThresholdRule.Max` must be set; no error should be thrown if both fields are populated
  * `MetricThresholdRule.Status` must not be null

[Sensu Tokens]: https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/tokens/
