### ISSUE TITLE
It's not possible to use `SENSU_BACKEND_ETCD_INITIAL_CLUSTER` environment variable when clustering Sensu Go

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#4638]
## Expected Behavior

According to the documentation, I should be able to use `SENSU_BACKEND_ETCD_INITIAL_CLUSTER` as an environment variable when creating a Sensu cluster with embedded etcd. 

## Current Behavior

Currently, errors like the ones below show when trying to start Sensu with the initial cluster specified as an environment variable:
```
{"component":"sensu-enterprise","error":"error starting etcd: error setting up initial cluster: parse \"http://1.2.3.4:2380\\\"\": invalid port \":2380\\\"\" after host","level":"fatal","msg":"error executing sensu-backend","time":"2022-02-25T19:59:22Z"}

{"component":"cmd","level":"info","msg":"attempting to connect to etcd server: http://1.2.3.4:2379","time":"2022-02-25T19:59:22Z"}

{"component":"cmd","level":"info","msg":"attempting to connect to etcd server: http://1.2.3.4:2379","time":"2022-02-25T19:59:35Z"}

{"component":"sensu-enterprise","error":"error starting etcd: error setting up initial cluster: parse \"http://1.2.3.4:2380\\\"\": invalid port \":2380\\\"\" after host","level":"fatal","msg":"error executing sensu-backend","time":"2022-02-25T19:59:35Z"}
```
This makes using the environment variable approach impossible to use and one is forced to rely on a command string version instead. 

## Possible Solution

Address the parsing issue in the Viper library so that it's possible to provide the initial cluster through an environment variable.

**Comment by c-kruse** [comment]
@asachs01 I wasn't able to recreate this. You got any more deets?

**Comment by c-kruse** [comment]
Example docker-compose where this appears to work as desired.

```
version: '3'
networks:
  sensu-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.9.8.0/24"
services:
  sensubackend1:
    image: sensu/sensu:latest
    environment:
      - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=ubuntu
      - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=U8un7u
      - SENSU_BACKEND_ETCD_INITIAL_CLUSTER=sensubackend1=http://10.9.8.9:2380,sensubackend2=http://10.9.8.10:2380,sensubackend3=http://10.9.8.11:2380
      - SENSU_BACKEND_ETCD_ADVERTISE_CLIENT_URLS=http://10.9.8.9:2379
      - SENSU_BACKEND_ETCD_CLIENT_URLS=http://10.9.8.9:2379 http://10.9.8.10:2379 http://10.9.8.11:2379
      - SENSU_BACKEND_ETCD_LISTEN_CLIENT_URLS= http://10.9.8.9:2379
      - SENSU_BACKEND_ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.9.8.9:2380
      - SENSU_BACKEND_ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - SENSU_BACKEND_ETCD_NAME=sensubackend1
      - SENSU_BACKEND_ETCD_INITIAL_CLUSTER_STATE=new
      - SENSU_BACKEND_STATE_DIR=/var/lib/sensu/sensu-backend
    command: sensu-backend start
    hostname: sensubackend1
    networks:
      sensu-net:
        ipv4_address: 10.9.8.9
  sensubackend2:
    image: sensu/sensu:latest
    environment:
      - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=ubuntu
      - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=U8un7u
      - SENSU_BACKEND_ETCD_INITIAL_CLUSTER=sensubackend1=http://10.9.8.9:2380,sensubackend2=http://10.9.8.10:2380,sensubackend3=http://10.9.8.11:2380
      - SENSU_BACKEND_ETCD_ADVERTISE_CLIENT_URLS=http://10.9.8.10:2379
      - SENSU_BACKEND_ETCD_CLIENT_URLS=http://10.9.8.9:2379 http://10.9.8.10:2379 http://10.9.8.11:2379
      - SENSU_BACKEND_ETCD_LISTEN_CLIENT_URLS= http://10.9.8.10:2379
      - SENSU_BACKEND_ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.9.8.10:2380
      - SENSU_BACKEND_ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - SENSU_BACKEND_ETCD_NAME=sensubackend2
      - SENSU_BACKEND_ETCD_INITIAL_CLUSTER_STATE=new
      - SENSU_BACKEND_STATE_DIR=/var/lib/sensu/sensu-backend
    command: sensu-backend start
    hostname: sensubackend2
    networks:
      sensu-net:
        ipv4_address: 10.9.8.10
  sensubackend3:
    image: sensu/sensu:latest
    environment:
      - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=ubuntu
      - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=U8un7u
      - SENSU_BACKEND_ETCD_INITIAL_CLUSTER=sensubackend1=http://10.9.8.9:2380,sensubackend2=http://10.9.8.10:2380,sensubackend3=http://10.9.8.11:2380
      - SENSU_BACKEND_ETCD_ADVERTISE_CLIENT_URLS=http://10.9.8.11:2379
      - SENSU_BACKEND_ETCD_CLIENT_URLS=http://10.9.8.9:2379 http://10.9.8.10:2379 http://10.9.8.11:2379
      - SENSU_BACKEND_ETCD_LISTEN_CLIENT_URLS= http://10.9.8.11:2379
      - SENSU_BACKEND_ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.9.8.11:2380
      - SENSU_BACKEND_ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - SENSU_BACKEND_ETCD_NAME=sensubackend3
      - SENSU_BACKEND_ETCD_INITIAL_CLUSTER_STATE=new
      - SENSU_BACKEND_STATE_DIR=/var/lib/sensu/sensu-backend
    command: sensu-backend start
    hostname: sensubackend3
    networks:
      sensu-net:
        ipv4_address: 10.9.8.11

```
