### ISSUE TITLE
Matching output_metric_thresholds should generate annotation(s)

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4652]
The new [Metric Threshold Service Checks](https://github.com/sensu/sensu-go/pull/4585) are working great in 6.7.0 pre-releases, but the resulting events don't provide any indication of the reason for the non-zero status. 

The agent should add one or more annotations indicating when the event status is the result of a metric threshold. 

### Annotation Content 

```
The value of <name> (<[comma-separated list of tag key=value]>) exceeded the configured threshold (<threshold_type>: <threshold>, actual: <value>).
```

Example

```yaml
  output_metric_thresholds:
    - name: system_cpu_used
      tags:
        - name: cpu
          value: cpu-total
      thresholds:
        - max: '{{ .annotations.system_cpu_used_warning_threshold | default "80.0" }}'
          status: 1
        - max: '{{ .annotations.system_cpu_used_critical_threshold | default "90.0" }}'
          status: 2
    - name: system_mem_used
      thresholds:
        - max: '{{ .annotations.system_mem_used_warning_threshold | default "80.0" }}'
          status: 1
        - max: '{{ .annotations.system_mem_used_critical_threshold | default "90.0" }}'
          status: 2
```

In the scenario where `system_cpu_used{cpu="cpu-total"}` was 95%, the resulting annotation should read: 

> The value of "system_cpu_used" (cpu="cpu-total") exceeded the configured threshold (max: 90.0, actual: 95.0).

### Annotations

* `sensu.io/output_metric_thresholds/<name>[.<tag_value>|.<tag_value>]/<threshold_type>/<status>`

  Set one annotation per matching metric threshold. 

  Status values should be strings (`0` = "ok", `1` = "warning", `2` = "critical"; all other values greater than 2 = "unknown")

  Using the same example from above, the resulting annotation names should be: 

  `sensu.io/output_metric_thresholds/system_cpu_used.cpu-total/max/warning`
  `sensu.io/output_metric_thresholds/system_cpu_used.cpu-total/max/critical`

* `sensu.io/event/notification` 

  Set this annotation for the most severe metric threshold, by status. 

  Using the same example from above, the resulting annotation value would be the threshold with the highest status (`2`): 

  > The value of "system_cpu_used" (cpu="cpu-total") exceeded the configured threshold (max: 90.0, actual: 95.0).

**Comment by calebhailey** [comment]
@fguimond if it's not too late let's adopt a slightly different annotation naming convention for notification annotation. 

Instead of a single `sensu.io/event/notification` annotation, we should adopt a `sensu.io/notifications/<status>` convention (e.g. `sensu.io/notifications/ok`, `sensu.io/notifications/warning`, `sensu.io/notifications/critical`, etc). 

In related news... how does the metric threshold evaluation handle a scenario when more than one threshold is exceeded with the same status (e.g. two thresholds with status `2`)? While iterating through the thresholds, do we only update `event.check.status` when the exceeded threshold value is **greater than** the current status? Or do we update `event.check.status` when the exceeded threshold value is **greater than or equal to** the current status? This probably wouldn't have mattered when we were only setting `event.check.status`, but now that we also want to set these annotations the logic matters more. In practice the difference is that certain "notification" annotations may represent the _first_ exceeded threshold of a given status, OR the _last_ exceeded threshold of a given status. 

Example: 

```yaml
  output_metric_thresholds:
    - name: metric1
      tags:
        - name: region
          value: us-west-1
      thresholds:
        - max: '90'
          status: 2
    - name: metric2
      tags:
        - name: region
          value: us-west-1
      thresholds:
        - max: '80'
          status: 1
        - max: '90'
          status: 2
```

If `metric1` and `metric2` are 95, what is the value of the `sensu.io/notifications/critical` annotation? 

Option 1: first exceeded threshold takes precedent ("greater than" logic)

```yaml
annotations:
  sensu.io/notifications/critical: The value of "metric1" (region="us-west-1") exceeded the configured threshold (max: 90.0, actual: 95.0).
```

Option 2: last exceeded threshold takes precedent ("greater than or equal" logic)

```yaml
annotations:
  sensu.io/notifications/critical: The value of "metric2" (region="us-west-1") exceeded the configured threshold (max: 90.0, actual: 95.0).
```
