### ISSUE TITLE
Allow specifying "self" as the resource in RBAC policies

### ISSUE THREAD

**Issue by theothertom** [sensu/sensu-go#4672]
Looking over the RBAC documentation, permissions can be applied in a granular way that would allow controlling access down to the agent level. What I'd like to be able to do is grant monitored hosts the ability to perform operations on themselves, but no other resources.

## Feature Suggestion
I'd like to be able to create an RBAC policy similar to the following
```yaml
type: Role
api_version: core/v2
metadata:
  name: prod-admin
spec:
  rules:
  - resources:
    - 'silences'
      resource_names:
      - "$caller.name"
      verbs:
      - create
```

## Context
What I'm wanting to do is allow the agents I'm monitoring to silence themselves (or individual checks).

The specific issue I'm facing is that, when we're provisioning a new host, Sensu is configured before all the services are installed/started. This results in sending alerts that will resolve automatically within a few minutes as the things they check are configured.

Another similar situation where it would be useful to have functionality like this is whilst performing application deployments - it would be nice if it were possible to allow hosts to silence specific checks while services restart.
