### ISSUE TITLE
Check Subdues are unreliable while crossing repeat intervals.

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-go#4847]
Check subdues are currently implemented as an open interval (i.e. begin < now < end). This is a problem when the operator specifies overlapping repeating intervals. For example: "Subdue between 4pm on Friday and 8am Monday" may be configured like this:
```
subdues:
- begin: "2022-08-19T16:00:00Z"
   end: "2022-08-19T23:59:59Z"
  repeat:
    - fridays
- begin: "2022-08-19T00:00:00Z"
  end: "2022-08-19T23:59:59Z"
  repeat:
    - saturdays
- begin: "2022-08-19T00:00:00Z"
  end: "2022-08-19T23:59:59Z"
  repeat:
    - sundays
- begin: "2022-08-19T00:00:00Z"
  end: "2022-08-19T08:00:00Z"
  repeat:
    - mondays
```

Since these are implemented as closed intervals (not to mention the extra precision that may make a date truly be between 23:59:59 and 00:00:00 the following day), this strategy leads to a small window where checks are still scheduled each night around midnight.

## Expected Behavior
TBD

**Comment by asachs01** [comment]
Hi @c-kruse I wanted to followup and see if you'd made any progress on this and if we have an idea as to when a fix might be released.

**Comment by c-kruse** [comment]
@asachs01  I hadn't made any progress, but it should be a fairly quick and contained fix. Adding to the next patch release.

**Comment by c-kruse** [comment]
@asachs01  I'm still planning on making adjustments to the implementation as it is indeed currently misleading. Read the code even more carefully and I've got an immediate workaround.

Instead of ending ranges at 23:59:59 in that day, users can specify an end time at 00:00:01 the next day and their sporadic missed subdues should go away.

i.e. this works without misses for 4PM friday until noon saturday 
```
subdues:
- begin: "2022-08-19T16:00:00Z"
   end: "2022-08-20T00:00:01Z"
  repeat:
    - fridays
- begin: "2022-08-19T00:00:00Z"
  end: "2022-08-19T12:00:00Z"
  repeat:
    - saturdays
```
