### ISSUE TITLE
add more metadata from cloud providers

### ISSUE THREAD

**Issue by jesusch** [sensu/sensu-go#4893]
Currently it seems only one property gets populated:

```
type: Entity
api_version: core/v2
metadata:
  name: ip-10-12-20-4
spec:
  system:
    cloud_provider: EC2

```
## Feature Suggestion
e.g. on AWS
http://169.254.169.254/latest/dynamic/instance-identity/document
```
{
  "accountId": "123456789012",
  "architecture": "x86_64",
  "availabilityZone": "eu-west-1c",
  "billingProducts": null,
  "devpayProductCodes": null,
  "marketplaceProductCodes": null,
  "imageId": "ami-asdf",
  "instanceId": "i-1234",
  "instanceType": "t3.xlarge",
  "kernelId": null,
  "pendingTime": "2022-09-09T11:18:23Z",
  "privateIp": "10.0.0.1",
  "ramdiskId": null,
  "region": "eu-west-1",
  "version": "2017-09-30"
}
```

would be awesome to have those available on the entity
even greater would be having instance tags (http://169.254.169.254/latest/meta-data/tags) as entity properties
